// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.autoscaling.v2beta1.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class PodsMetricStatus {
    private final String currentAverageValue;
    private final String metricName;
    private final @Nullable io.pulumi.kubernetes.meta.v1.outputs.LabelSelector selector;

    @OutputCustomType.Constructor({"currentAverageValue","metricName","selector"})
    private PodsMetricStatus(
        String currentAverageValue,
        String metricName,
        @Nullable io.pulumi.kubernetes.meta.v1.outputs.LabelSelector selector) {
        this.currentAverageValue = Objects.requireNonNull(currentAverageValue);
        this.metricName = Objects.requireNonNull(metricName);
        this.selector = selector;
    }

    public String getCurrentAverageValue() {
        return this.currentAverageValue;
    }
    public String getMetricName() {
        return this.metricName;
    }
    public Optional<io.pulumi.kubernetes.meta.v1.outputs.LabelSelector> getSelector() {
        return Optional.ofNullable(this.selector);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(PodsMetricStatus defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private String currentAverageValue;
        private String metricName;
        private @Nullable io.pulumi.kubernetes.meta.v1.outputs.LabelSelector selector;

        public Builder() {
    	      // Empty
        }

        public Builder(PodsMetricStatus defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.currentAverageValue = defaults.currentAverageValue;
    	      this.metricName = defaults.metricName;
    	      this.selector = defaults.selector;
        }

        public Builder setCurrentAverageValue(String currentAverageValue) {
            this.currentAverageValue = Objects.requireNonNull(currentAverageValue);
            return this;
        }

        public Builder setMetricName(String metricName) {
            this.metricName = Objects.requireNonNull(metricName);
            return this;
        }

        public Builder setSelector(@Nullable io.pulumi.kubernetes.meta.v1.outputs.LabelSelector selector) {
            this.selector = selector;
            return this;
        }

        public PodsMetricStatus build() {
            return new PodsMetricStatus(currentAverageValue, metricName, selector);
        }
    }
}
