// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.autoscaling.v2beta1.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class ResourceMetricSource {
    private final String name;
    private final @Nullable Integer targetAverageUtilization;
    private final @Nullable String targetAverageValue;

    @OutputCustomType.Constructor({"name","targetAverageUtilization","targetAverageValue"})
    private ResourceMetricSource(
        String name,
        @Nullable Integer targetAverageUtilization,
        @Nullable String targetAverageValue) {
        this.name = Objects.requireNonNull(name);
        this.targetAverageUtilization = targetAverageUtilization;
        this.targetAverageValue = targetAverageValue;
    }

    public String getName() {
        return this.name;
    }
    public Optional<Integer> getTargetAverageUtilization() {
        return Optional.ofNullable(this.targetAverageUtilization);
    }
    public Optional<String> getTargetAverageValue() {
        return Optional.ofNullable(this.targetAverageValue);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ResourceMetricSource defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private String name;
        private @Nullable Integer targetAverageUtilization;
        private @Nullable String targetAverageValue;

        public Builder() {
    	      // Empty
        }

        public Builder(ResourceMetricSource defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.name = defaults.name;
    	      this.targetAverageUtilization = defaults.targetAverageUtilization;
    	      this.targetAverageValue = defaults.targetAverageValue;
        }

        public Builder setName(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }

        public Builder setTargetAverageUtilization(@Nullable Integer targetAverageUtilization) {
            this.targetAverageUtilization = targetAverageUtilization;
            return this;
        }

        public Builder setTargetAverageValue(@Nullable String targetAverageValue) {
            this.targetAverageValue = targetAverageValue;
            return this;
        }

        public ResourceMetricSource build() {
            return new ResourceMetricSource(name, targetAverageUtilization, targetAverageValue);
        }
    }
}
