// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.authentication.v1.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class TokenReviewSpec {
    private final @Nullable List<String> audiences;
    private final @Nullable String token;

    @OutputCustomType.Constructor({"audiences","token"})
    private TokenReviewSpec(
        @Nullable List<String> audiences,
        @Nullable String token) {
        this.audiences = audiences;
        this.token = token;
    }

    public List<String> getAudiences() {
        return this.audiences == null ? List.of() : this.audiences;
    }
    public Optional<String> getToken() {
        return Optional.ofNullable(this.token);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(TokenReviewSpec defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable List<String> audiences;
        private @Nullable String token;

        public Builder() {
    	      // Empty
        }

        public Builder(TokenReviewSpec defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.audiences = defaults.audiences;
    	      this.token = defaults.token;
        }

        public Builder setAudiences(@Nullable List<String> audiences) {
            this.audiences = audiences;
            return this;
        }

        public Builder setToken(@Nullable String token) {
            this.token = token;
            return this;
        }

        public TokenReviewSpec build() {
            return new TokenReviewSpec(audiences, token);
        }
    }
}
