// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.apps.v1beta1.inputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;


public final class RollingUpdateStatefulSetStrategyArgs extends io.pulumi.resources.ResourceArgs {

    public static final RollingUpdateStatefulSetStrategyArgs Empty = new RollingUpdateStatefulSetStrategyArgs();

    @InputImport(name="partition")
    private final @Nullable Input<Integer> partition;

    public Input<Integer> getPartition() {
        return this.partition == null ? Input.empty() : this.partition;
    }

    public RollingUpdateStatefulSetStrategyArgs(@Nullable Input<Integer> partition) {
        this.partition = partition;
    }

    private RollingUpdateStatefulSetStrategyArgs() {
        this.partition = Input.empty();
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(RollingUpdateStatefulSetStrategyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable Input<Integer> partition;

        public Builder() {
    	      // Empty
        }

        public Builder(RollingUpdateStatefulSetStrategyArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.partition = defaults.partition;
        }

        public Builder setPartition(@Nullable Input<Integer> partition) {
            this.partition = partition;
            return this;
        }

        public Builder setPartition(@Nullable Integer partition) {
            this.partition = Input.ofNullable(partition);
            return this;
        }

        public RollingUpdateStatefulSetStrategyArgs build() {
            return new RollingUpdateStatefulSetStrategyArgs(partition);
        }
    }
}
