// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.rbac.v1alpha1;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;
import io.pulumi.kubernetes.rbac.v1alpha1.inputs.*;

@ResourceType(type="kubernetes:rbac.authorization.k8s.io/v1alpha1:ClusterRoleBinding")
public class ClusterRoleBinding extends io.pulumi.kubernetes.KubernetesResource {
    @OutputExport(name="apiVersion", type=String.class, parameters={})
    private Output</* @Nullable */ String> apiVersion;

    public Output</* @Nullable */ String> getApiVersion() {
        return this.apiVersion;
    }
    @OutputExport(name="kind", type=String.class, parameters={})
    private Output</* @Nullable */ String> kind;

    public Output</* @Nullable */ String> getKind() {
        return this.kind;
    }
    @OutputExport(name="metadata", type=io.pulumi.kubernetes.meta.v1.outputs.ObjectMeta.class, parameters={})
    private Output</* @Nullable */ io.pulumi.kubernetes.meta.v1.outputs.ObjectMeta> metadata;

    public Output</* @Nullable */ io.pulumi.kubernetes.meta.v1.outputs.ObjectMeta> getMetadata() {
        return this.metadata;
    }
    @OutputExport(name="roleRef", type=io.pulumi.kubernetes.rbac.v1alpha1.outputs.RoleRef.class, parameters={})
    private Output<io.pulumi.kubernetes.rbac.v1alpha1.outputs.RoleRef> roleRef;

    public Output<io.pulumi.kubernetes.rbac.v1alpha1.outputs.RoleRef> getRoleRef() {
        return this.roleRef;
    }
    @OutputExport(name="subjects", type=List.class, parameters={io.pulumi.kubernetes.rbac.v1alpha1.outputs.Subject.class})
    private Output</* @Nullable */ List<io.pulumi.kubernetes.rbac.v1alpha1.outputs.Subject>> subjects;

    public Output</* @Nullable */ List<io.pulumi.kubernetes.rbac.v1alpha1.outputs.Subject>> getSubjects() {
        return this.subjects;
    }

    public ClusterRoleBinding(String name, ClusterRoleBindingArgs args, @Nullable io.pulumi.resources.CustomResourceOptions options) {
        super("kubernetes:rbac.authorization.k8s.io/v1alpha1:ClusterRoleBinding", name, makeArgs(args), makeResourceOptions(options, Input.empty()));
    }

    private ClusterRoleBinding(String name, Input<String> id, @Nullable io.pulumi.resources.CustomResourceOptions options) {
        super("kubernetes:rbac.authorization.k8s.io/v1alpha1:ClusterRoleBinding", name, null, makeResourceOptions(options, id));
    }

    private static ClusterRoleBindingArgs makeArgs(ClusterRoleBindingArgs args) {
        var builder = args == null ? ClusterRoleBindingArgs.builder() : ClusterRoleBindingArgs.builder(args);
        return builder
            .setApiVersion("rbac.authorization.k8s.io/v1alpha1")
            .setKind("ClusterRoleBinding")
            .build();
    }

    private static io.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable io.pulumi.resources.CustomResourceOptions options, @Nullable Input<String> id) {
        var defaultOptions = io.pulumi.resources.CustomResourceOptions.builder()
            .setVersion(Utilities.getVersion())
            .setAliases(List.of(
                Input.of(Alias.builder().setType("kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding").build()),
                Input.of(Alias.builder().setType("kubernetes:rbac.authorization.k8s.io/v1beta1:ClusterRoleBinding").build())
            ))
            .build();
        return io.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    public static ClusterRoleBinding get(String name, Input<String> id, @Nullable io.pulumi.resources.CustomResourceOptions options) {
        return new ClusterRoleBinding(name, id, options);
    }
}
