// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.extensions.v1beta1;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;
import io.pulumi.kubernetes.extensions.v1beta1.inputs.*;

@Deprecated /* extensions/v1beta1/ReplicaSet is deprecated by apps/v1/ReplicaSet and not supported by Kubernetes v1.16+ clusters. */
@ResourceType(type="kubernetes:extensions/v1beta1:ReplicaSet")
public class ReplicaSet extends io.pulumi.kubernetes.KubernetesResource {
    @OutputExport(name="apiVersion", type=String.class, parameters={})
    private Output</* @Nullable */ String> apiVersion;

    public Output</* @Nullable */ String> getApiVersion() {
        return this.apiVersion;
    }
    @OutputExport(name="kind", type=String.class, parameters={})
    private Output</* @Nullable */ String> kind;

    public Output</* @Nullable */ String> getKind() {
        return this.kind;
    }
    @OutputExport(name="metadata", type=io.pulumi.kubernetes.meta.v1.outputs.ObjectMeta.class, parameters={})
    private Output</* @Nullable */ io.pulumi.kubernetes.meta.v1.outputs.ObjectMeta> metadata;

    public Output</* @Nullable */ io.pulumi.kubernetes.meta.v1.outputs.ObjectMeta> getMetadata() {
        return this.metadata;
    }
    @OutputExport(name="spec", type=io.pulumi.kubernetes.extensions.v1beta1.outputs.ReplicaSetSpec.class, parameters={})
    private Output</* @Nullable */ io.pulumi.kubernetes.extensions.v1beta1.outputs.ReplicaSetSpec> spec;

    public Output</* @Nullable */ io.pulumi.kubernetes.extensions.v1beta1.outputs.ReplicaSetSpec> getSpec() {
        return this.spec;
    }
    @OutputExport(name="status", type=io.pulumi.kubernetes.extensions.v1beta1.outputs.ReplicaSetStatus.class, parameters={})
    private Output</* @Nullable */ io.pulumi.kubernetes.extensions.v1beta1.outputs.ReplicaSetStatus> status;

    public Output</* @Nullable */ io.pulumi.kubernetes.extensions.v1beta1.outputs.ReplicaSetStatus> getStatus() {
        return this.status;
    }

    public ReplicaSet(String name, @Nullable ReplicaSetArgs args, @Nullable io.pulumi.resources.CustomResourceOptions options) {
        super("kubernetes:extensions/v1beta1:ReplicaSet", name, makeArgs(args), makeResourceOptions(options, Input.empty()));
    }

    private ReplicaSet(String name, Input<String> id, @Nullable io.pulumi.resources.CustomResourceOptions options) {
        super("kubernetes:extensions/v1beta1:ReplicaSet", name, null, makeResourceOptions(options, id));
    }

    private static ReplicaSetArgs makeArgs(@Nullable ReplicaSetArgs args) {
        var builder = args == null ? ReplicaSetArgs.builder() : ReplicaSetArgs.builder(args);
        return builder
            .setApiVersion("extensions/v1beta1")
            .setKind("ReplicaSet")
            .build();
    }

    private static io.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable io.pulumi.resources.CustomResourceOptions options, @Nullable Input<String> id) {
        var defaultOptions = io.pulumi.resources.CustomResourceOptions.builder()
            .setVersion(Utilities.getVersion())
            .setAliases(List.of(
                Input.of(Alias.builder().setType("kubernetes:apps/v1:ReplicaSet").build()),
                Input.of(Alias.builder().setType("kubernetes:apps/v1beta2:ReplicaSet").build())
            ))
            .build();
        return io.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    public static ReplicaSet get(String name, Input<String> id, @Nullable io.pulumi.resources.CustomResourceOptions options) {
        return new ReplicaSet(name, id, options);
    }
}
