// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.admissionregistration.v1.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class MutatingWebhook {
    private final List<String> admissionReviewVersions;
    private final io.pulumi.kubernetes.admissionregistration.v1.outputs.WebhookClientConfig clientConfig;
    private final @Nullable String failurePolicy;
    private final @Nullable String matchPolicy;
    private final String name;
    private final @Nullable io.pulumi.kubernetes.meta.v1.outputs.LabelSelector namespaceSelector;
    private final @Nullable io.pulumi.kubernetes.meta.v1.outputs.LabelSelector objectSelector;
    private final @Nullable String reinvocationPolicy;
    private final @Nullable List<io.pulumi.kubernetes.admissionregistration.v1.outputs.RuleWithOperations> rules;
    private final String sideEffects;
    private final @Nullable Integer timeoutSeconds;

    @OutputCustomType.Constructor({"admissionReviewVersions","clientConfig","failurePolicy","matchPolicy","name","namespaceSelector","objectSelector","reinvocationPolicy","rules","sideEffects","timeoutSeconds"})
    private MutatingWebhook(
        List<String> admissionReviewVersions,
        io.pulumi.kubernetes.admissionregistration.v1.outputs.WebhookClientConfig clientConfig,
        @Nullable String failurePolicy,
        @Nullable String matchPolicy,
        String name,
        @Nullable io.pulumi.kubernetes.meta.v1.outputs.LabelSelector namespaceSelector,
        @Nullable io.pulumi.kubernetes.meta.v1.outputs.LabelSelector objectSelector,
        @Nullable String reinvocationPolicy,
        @Nullable List<io.pulumi.kubernetes.admissionregistration.v1.outputs.RuleWithOperations> rules,
        String sideEffects,
        @Nullable Integer timeoutSeconds) {
        this.admissionReviewVersions = Objects.requireNonNull(admissionReviewVersions);
        this.clientConfig = Objects.requireNonNull(clientConfig);
        this.failurePolicy = failurePolicy;
        this.matchPolicy = matchPolicy;
        this.name = Objects.requireNonNull(name);
        this.namespaceSelector = namespaceSelector;
        this.objectSelector = objectSelector;
        this.reinvocationPolicy = reinvocationPolicy;
        this.rules = rules;
        this.sideEffects = Objects.requireNonNull(sideEffects);
        this.timeoutSeconds = timeoutSeconds;
    }

    public List<String> getAdmissionReviewVersions() {
        return this.admissionReviewVersions;
    }
    public io.pulumi.kubernetes.admissionregistration.v1.outputs.WebhookClientConfig getClientConfig() {
        return this.clientConfig;
    }
    public Optional<String> getFailurePolicy() {
        return Optional.ofNullable(this.failurePolicy);
    }
    public Optional<String> getMatchPolicy() {
        return Optional.ofNullable(this.matchPolicy);
    }
    public String getName() {
        return this.name;
    }
    public Optional<io.pulumi.kubernetes.meta.v1.outputs.LabelSelector> getNamespaceSelector() {
        return Optional.ofNullable(this.namespaceSelector);
    }
    public Optional<io.pulumi.kubernetes.meta.v1.outputs.LabelSelector> getObjectSelector() {
        return Optional.ofNullable(this.objectSelector);
    }
    public Optional<String> getReinvocationPolicy() {
        return Optional.ofNullable(this.reinvocationPolicy);
    }
    public List<io.pulumi.kubernetes.admissionregistration.v1.outputs.RuleWithOperations> getRules() {
        return this.rules == null ? List.of() : this.rules;
    }
    public String getSideEffects() {
        return this.sideEffects;
    }
    public Optional<Integer> getTimeoutSeconds() {
        return Optional.ofNullable(this.timeoutSeconds);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(MutatingWebhook defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private List<String> admissionReviewVersions;
        private io.pulumi.kubernetes.admissionregistration.v1.outputs.WebhookClientConfig clientConfig;
        private @Nullable String failurePolicy;
        private @Nullable String matchPolicy;
        private String name;
        private @Nullable io.pulumi.kubernetes.meta.v1.outputs.LabelSelector namespaceSelector;
        private @Nullable io.pulumi.kubernetes.meta.v1.outputs.LabelSelector objectSelector;
        private @Nullable String reinvocationPolicy;
        private @Nullable List<io.pulumi.kubernetes.admissionregistration.v1.outputs.RuleWithOperations> rules;
        private String sideEffects;
        private @Nullable Integer timeoutSeconds;

        public Builder() {
    	      // Empty
        }

        public Builder(MutatingWebhook defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.admissionReviewVersions = defaults.admissionReviewVersions;
    	      this.clientConfig = defaults.clientConfig;
    	      this.failurePolicy = defaults.failurePolicy;
    	      this.matchPolicy = defaults.matchPolicy;
    	      this.name = defaults.name;
    	      this.namespaceSelector = defaults.namespaceSelector;
    	      this.objectSelector = defaults.objectSelector;
    	      this.reinvocationPolicy = defaults.reinvocationPolicy;
    	      this.rules = defaults.rules;
    	      this.sideEffects = defaults.sideEffects;
    	      this.timeoutSeconds = defaults.timeoutSeconds;
        }

        public Builder setAdmissionReviewVersions(List<String> admissionReviewVersions) {
            this.admissionReviewVersions = Objects.requireNonNull(admissionReviewVersions);
            return this;
        }

        public Builder setClientConfig(io.pulumi.kubernetes.admissionregistration.v1.outputs.WebhookClientConfig clientConfig) {
            this.clientConfig = Objects.requireNonNull(clientConfig);
            return this;
        }

        public Builder setFailurePolicy(@Nullable String failurePolicy) {
            this.failurePolicy = failurePolicy;
            return this;
        }

        public Builder setMatchPolicy(@Nullable String matchPolicy) {
            this.matchPolicy = matchPolicy;
            return this;
        }

        public Builder setName(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }

        public Builder setNamespaceSelector(@Nullable io.pulumi.kubernetes.meta.v1.outputs.LabelSelector namespaceSelector) {
            this.namespaceSelector = namespaceSelector;
            return this;
        }

        public Builder setObjectSelector(@Nullable io.pulumi.kubernetes.meta.v1.outputs.LabelSelector objectSelector) {
            this.objectSelector = objectSelector;
            return this;
        }

        public Builder setReinvocationPolicy(@Nullable String reinvocationPolicy) {
            this.reinvocationPolicy = reinvocationPolicy;
            return this;
        }

        public Builder setRules(@Nullable List<io.pulumi.kubernetes.admissionregistration.v1.outputs.RuleWithOperations> rules) {
            this.rules = rules;
            return this;
        }

        public Builder setSideEffects(String sideEffects) {
            this.sideEffects = Objects.requireNonNull(sideEffects);
            return this;
        }

        public Builder setTimeoutSeconds(@Nullable Integer timeoutSeconds) {
            this.timeoutSeconds = timeoutSeconds;
            return this;
        }

        public MutatingWebhook build() {
            return new MutatingWebhook(admissionReviewVersions, clientConfig, failurePolicy, matchPolicy, name, namespaceSelector, objectSelector, reinvocationPolicy, rules, sideEffects, timeoutSeconds);
        }
    }
}
