// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.apiextensions.v1.inputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;


public final class CustomResourceDefinitionStatusArgs extends io.pulumi.resources.ResourceArgs {

    public static final CustomResourceDefinitionStatusArgs Empty = new CustomResourceDefinitionStatusArgs();

    @InputImport(name="acceptedNames", required=true)
    private final Input<io.pulumi.kubernetes.apiextensions.v1.inputs.CustomResourceDefinitionNamesArgs> acceptedNames;

    public Input<io.pulumi.kubernetes.apiextensions.v1.inputs.CustomResourceDefinitionNamesArgs> getAcceptedNames() {
        return this.acceptedNames;
    }

    @InputImport(name="conditions")
    private final @Nullable Input<List<io.pulumi.kubernetes.apiextensions.v1.inputs.CustomResourceDefinitionConditionArgs>> conditions;

    public Input<List<io.pulumi.kubernetes.apiextensions.v1.inputs.CustomResourceDefinitionConditionArgs>> getConditions() {
        return this.conditions == null ? Input.empty() : this.conditions;
    }

    @InputImport(name="storedVersions", required=true)
    private final Input<List<String>> storedVersions;

    public Input<List<String>> getStoredVersions() {
        return this.storedVersions;
    }

    public CustomResourceDefinitionStatusArgs(
        Input<io.pulumi.kubernetes.apiextensions.v1.inputs.CustomResourceDefinitionNamesArgs> acceptedNames,
        @Nullable Input<List<io.pulumi.kubernetes.apiextensions.v1.inputs.CustomResourceDefinitionConditionArgs>> conditions,
        Input<List<String>> storedVersions) {
        this.acceptedNames = Objects.requireNonNull(acceptedNames, "expected parameter 'acceptedNames' to be non-null");
        this.conditions = conditions;
        this.storedVersions = Objects.requireNonNull(storedVersions, "expected parameter 'storedVersions' to be non-null");
    }

    private CustomResourceDefinitionStatusArgs() {
        this.acceptedNames = Input.empty();
        this.conditions = Input.empty();
        this.storedVersions = Input.empty();
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(CustomResourceDefinitionStatusArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private Input<io.pulumi.kubernetes.apiextensions.v1.inputs.CustomResourceDefinitionNamesArgs> acceptedNames;
        private @Nullable Input<List<io.pulumi.kubernetes.apiextensions.v1.inputs.CustomResourceDefinitionConditionArgs>> conditions;
        private Input<List<String>> storedVersions;

        public Builder() {
    	      // Empty
        }

        public Builder(CustomResourceDefinitionStatusArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.acceptedNames = defaults.acceptedNames;
    	      this.conditions = defaults.conditions;
    	      this.storedVersions = defaults.storedVersions;
        }

        public Builder setAcceptedNames(Input<io.pulumi.kubernetes.apiextensions.v1.inputs.CustomResourceDefinitionNamesArgs> acceptedNames) {
            this.acceptedNames = Objects.requireNonNull(acceptedNames);
            return this;
        }

        public Builder setAcceptedNames(io.pulumi.kubernetes.apiextensions.v1.inputs.CustomResourceDefinitionNamesArgs acceptedNames) {
            this.acceptedNames = Input.of(Objects.requireNonNull(acceptedNames));
            return this;
        }

        public Builder setConditions(@Nullable Input<List<io.pulumi.kubernetes.apiextensions.v1.inputs.CustomResourceDefinitionConditionArgs>> conditions) {
            this.conditions = conditions;
            return this;
        }

        public Builder setConditions(@Nullable List<io.pulumi.kubernetes.apiextensions.v1.inputs.CustomResourceDefinitionConditionArgs> conditions) {
            this.conditions = Input.ofNullable(conditions);
            return this;
        }

        public Builder setStoredVersions(Input<List<String>> storedVersions) {
            this.storedVersions = Objects.requireNonNull(storedVersions);
            return this;
        }

        public Builder setStoredVersions(List<String> storedVersions) {
            this.storedVersions = Input.of(Objects.requireNonNull(storedVersions));
            return this;
        }

        public CustomResourceDefinitionStatusArgs build() {
            return new CustomResourceDefinitionStatusArgs(acceptedNames, conditions, storedVersions);
        }
    }
}
