// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.apiextensions.v1.inputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;


public final class CustomResourceConversionArgs extends io.pulumi.resources.ResourceArgs {

    public static final CustomResourceConversionArgs Empty = new CustomResourceConversionArgs();

    @InputImport(name="strategy", required=true)
    private final Input<String> strategy;

    public Input<String> getStrategy() {
        return this.strategy;
    }

    @InputImport(name="webhook")
    private final @Nullable Input<io.pulumi.kubernetes.apiextensions.v1.inputs.WebhookConversionArgs> webhook;

    public Input<io.pulumi.kubernetes.apiextensions.v1.inputs.WebhookConversionArgs> getWebhook() {
        return this.webhook == null ? Input.empty() : this.webhook;
    }

    public CustomResourceConversionArgs(
        Input<String> strategy,
        @Nullable Input<io.pulumi.kubernetes.apiextensions.v1.inputs.WebhookConversionArgs> webhook) {
        this.strategy = Objects.requireNonNull(strategy, "expected parameter 'strategy' to be non-null");
        this.webhook = webhook;
    }

    private CustomResourceConversionArgs() {
        this.strategy = Input.empty();
        this.webhook = Input.empty();
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(CustomResourceConversionArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private Input<String> strategy;
        private @Nullable Input<io.pulumi.kubernetes.apiextensions.v1.inputs.WebhookConversionArgs> webhook;

        public Builder() {
    	      // Empty
        }

        public Builder(CustomResourceConversionArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.strategy = defaults.strategy;
    	      this.webhook = defaults.webhook;
        }

        public Builder setStrategy(Input<String> strategy) {
            this.strategy = Objects.requireNonNull(strategy);
            return this;
        }

        public Builder setStrategy(String strategy) {
            this.strategy = Input.of(Objects.requireNonNull(strategy));
            return this;
        }

        public Builder setWebhook(@Nullable Input<io.pulumi.kubernetes.apiextensions.v1.inputs.WebhookConversionArgs> webhook) {
            this.webhook = webhook;
            return this;
        }

        public Builder setWebhook(@Nullable io.pulumi.kubernetes.apiextensions.v1.inputs.WebhookConversionArgs webhook) {
            this.webhook = Input.ofNullable(webhook);
            return this;
        }

        public CustomResourceConversionArgs build() {
            return new CustomResourceConversionArgs(strategy, webhook);
        }
    }
}
