// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.certificates.v1beta1;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;
import io.pulumi.kubernetes.certificates.v1beta1.inputs.*;

@ResourceType(type="kubernetes:certificates.k8s.io/v1beta1:CertificateSigningRequest")
public class CertificateSigningRequest extends io.pulumi.kubernetes.KubernetesResource {
    @OutputExport(name="apiVersion", type=String.class, parameters={})
    private Output</* @Nullable */ String> apiVersion;

    public Output</* @Nullable */ String> getApiVersion() {
        return this.apiVersion;
    }
    @OutputExport(name="kind", type=String.class, parameters={})
    private Output</* @Nullable */ String> kind;

    public Output</* @Nullable */ String> getKind() {
        return this.kind;
    }
    @OutputExport(name="metadata", type=io.pulumi.kubernetes.meta.v1.outputs.ObjectMeta.class, parameters={})
    private Output</* @Nullable */ io.pulumi.kubernetes.meta.v1.outputs.ObjectMeta> metadata;

    public Output</* @Nullable */ io.pulumi.kubernetes.meta.v1.outputs.ObjectMeta> getMetadata() {
        return this.metadata;
    }
    @OutputExport(name="spec", type=io.pulumi.kubernetes.certificates.v1beta1.outputs.CertificateSigningRequestSpec.class, parameters={})
    private Output</* @Nullable */ io.pulumi.kubernetes.certificates.v1beta1.outputs.CertificateSigningRequestSpec> spec;

    public Output</* @Nullable */ io.pulumi.kubernetes.certificates.v1beta1.outputs.CertificateSigningRequestSpec> getSpec() {
        return this.spec;
    }
    @OutputExport(name="status", type=io.pulumi.kubernetes.certificates.v1beta1.outputs.CertificateSigningRequestStatus.class, parameters={})
    private Output</* @Nullable */ io.pulumi.kubernetes.certificates.v1beta1.outputs.CertificateSigningRequestStatus> status;

    public Output</* @Nullable */ io.pulumi.kubernetes.certificates.v1beta1.outputs.CertificateSigningRequestStatus> getStatus() {
        return this.status;
    }

    public CertificateSigningRequest(String name, @Nullable CertificateSigningRequestArgs args, @Nullable io.pulumi.resources.CustomResourceOptions options) {
        super("kubernetes:certificates.k8s.io/v1beta1:CertificateSigningRequest", name, makeArgs(args), makeResourceOptions(options, Input.empty()));
    }

    private CertificateSigningRequest(String name, Input<String> id, @Nullable io.pulumi.resources.CustomResourceOptions options) {
        super("kubernetes:certificates.k8s.io/v1beta1:CertificateSigningRequest", name, null, makeResourceOptions(options, id));
    }

    private static CertificateSigningRequestArgs makeArgs(@Nullable CertificateSigningRequestArgs args) {
        var builder = args == null ? CertificateSigningRequestArgs.builder() : CertificateSigningRequestArgs.builder(args);
        return builder
            .setApiVersion("certificates.k8s.io/v1beta1")
            .setKind("CertificateSigningRequest")
            .build();
    }

    private static io.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable io.pulumi.resources.CustomResourceOptions options, @Nullable Input<String> id) {
        var defaultOptions = io.pulumi.resources.CustomResourceOptions.builder()
            .setVersion(Utilities.getVersion())
            .setAliases(List.of(
                Input.of(Alias.builder().setType("kubernetes:certificates.k8s.io/v1:CertificateSigningRequest").build())
            ))
            .build();
        return io.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    public static CertificateSigningRequest get(String name, Input<String> id, @Nullable io.pulumi.resources.CustomResourceOptions options) {
        return new CertificateSigningRequest(name, id, options);
    }
}
