// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.networking.v1.inputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;


public final class NetworkPolicyEgressRuleArgs extends io.pulumi.resources.ResourceArgs {

    public static final NetworkPolicyEgressRuleArgs Empty = new NetworkPolicyEgressRuleArgs();

    @InputImport(name="ports")
    private final @Nullable Input<List<io.pulumi.kubernetes.networking.v1.inputs.NetworkPolicyPortArgs>> ports;

    public Input<List<io.pulumi.kubernetes.networking.v1.inputs.NetworkPolicyPortArgs>> getPorts() {
        return this.ports == null ? Input.empty() : this.ports;
    }

    @InputImport(name="to")
    private final @Nullable Input<List<io.pulumi.kubernetes.networking.v1.inputs.NetworkPolicyPeerArgs>> to;

    public Input<List<io.pulumi.kubernetes.networking.v1.inputs.NetworkPolicyPeerArgs>> getTo() {
        return this.to == null ? Input.empty() : this.to;
    }

    public NetworkPolicyEgressRuleArgs(
        @Nullable Input<List<io.pulumi.kubernetes.networking.v1.inputs.NetworkPolicyPortArgs>> ports,
        @Nullable Input<List<io.pulumi.kubernetes.networking.v1.inputs.NetworkPolicyPeerArgs>> to) {
        this.ports = ports;
        this.to = to;
    }

    private NetworkPolicyEgressRuleArgs() {
        this.ports = Input.empty();
        this.to = Input.empty();
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NetworkPolicyEgressRuleArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable Input<List<io.pulumi.kubernetes.networking.v1.inputs.NetworkPolicyPortArgs>> ports;
        private @Nullable Input<List<io.pulumi.kubernetes.networking.v1.inputs.NetworkPolicyPeerArgs>> to;

        public Builder() {
    	      // Empty
        }

        public Builder(NetworkPolicyEgressRuleArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.ports = defaults.ports;
    	      this.to = defaults.to;
        }

        public Builder setPorts(@Nullable Input<List<io.pulumi.kubernetes.networking.v1.inputs.NetworkPolicyPortArgs>> ports) {
            this.ports = ports;
            return this;
        }

        public Builder setPorts(@Nullable List<io.pulumi.kubernetes.networking.v1.inputs.NetworkPolicyPortArgs> ports) {
            this.ports = Input.ofNullable(ports);
            return this;
        }

        public Builder setTo(@Nullable Input<List<io.pulumi.kubernetes.networking.v1.inputs.NetworkPolicyPeerArgs>> to) {
            this.to = to;
            return this;
        }

        public Builder setTo(@Nullable List<io.pulumi.kubernetes.networking.v1.inputs.NetworkPolicyPeerArgs> to) {
            this.to = Input.ofNullable(to);
            return this;
        }

        public NetworkPolicyEgressRuleArgs build() {
            return new NetworkPolicyEgressRuleArgs(ports, to);
        }
    }
}
