// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.networking.v1.inputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;


public final class NetworkPolicyIngressRuleArgs extends io.pulumi.resources.ResourceArgs {

    public static final NetworkPolicyIngressRuleArgs Empty = new NetworkPolicyIngressRuleArgs();

    @InputImport(name="from")
    private final @Nullable Input<List<io.pulumi.kubernetes.networking.v1.inputs.NetworkPolicyPeerArgs>> from;

    public Input<List<io.pulumi.kubernetes.networking.v1.inputs.NetworkPolicyPeerArgs>> getFrom() {
        return this.from == null ? Input.empty() : this.from;
    }

    @InputImport(name="ports")
    private final @Nullable Input<List<io.pulumi.kubernetes.networking.v1.inputs.NetworkPolicyPortArgs>> ports;

    public Input<List<io.pulumi.kubernetes.networking.v1.inputs.NetworkPolicyPortArgs>> getPorts() {
        return this.ports == null ? Input.empty() : this.ports;
    }

    public NetworkPolicyIngressRuleArgs(
        @Nullable Input<List<io.pulumi.kubernetes.networking.v1.inputs.NetworkPolicyPeerArgs>> from,
        @Nullable Input<List<io.pulumi.kubernetes.networking.v1.inputs.NetworkPolicyPortArgs>> ports) {
        this.from = from;
        this.ports = ports;
    }

    private NetworkPolicyIngressRuleArgs() {
        this.from = Input.empty();
        this.ports = Input.empty();
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NetworkPolicyIngressRuleArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable Input<List<io.pulumi.kubernetes.networking.v1.inputs.NetworkPolicyPeerArgs>> from;
        private @Nullable Input<List<io.pulumi.kubernetes.networking.v1.inputs.NetworkPolicyPortArgs>> ports;

        public Builder() {
    	      // Empty
        }

        public Builder(NetworkPolicyIngressRuleArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.from = defaults.from;
    	      this.ports = defaults.ports;
        }

        public Builder setFrom(@Nullable Input<List<io.pulumi.kubernetes.networking.v1.inputs.NetworkPolicyPeerArgs>> from) {
            this.from = from;
            return this;
        }

        public Builder setFrom(@Nullable List<io.pulumi.kubernetes.networking.v1.inputs.NetworkPolicyPeerArgs> from) {
            this.from = Input.ofNullable(from);
            return this;
        }

        public Builder setPorts(@Nullable Input<List<io.pulumi.kubernetes.networking.v1.inputs.NetworkPolicyPortArgs>> ports) {
            this.ports = ports;
            return this;
        }

        public Builder setPorts(@Nullable List<io.pulumi.kubernetes.networking.v1.inputs.NetworkPolicyPortArgs> ports) {
            this.ports = Input.ofNullable(ports);
            return this;
        }

        public NetworkPolicyIngressRuleArgs build() {
            return new NetworkPolicyIngressRuleArgs(from, ports);
        }
    }
}
