// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.authorization.v1.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class SelfSubjectAccessReviewSpec {
    private final @Nullable io.pulumi.kubernetes.authorization.v1.outputs.NonResourceAttributes nonResourceAttributes;
    private final @Nullable io.pulumi.kubernetes.authorization.v1.outputs.ResourceAttributes resourceAttributes;

    @OutputCustomType.Constructor({"nonResourceAttributes","resourceAttributes"})
    private SelfSubjectAccessReviewSpec(
        @Nullable io.pulumi.kubernetes.authorization.v1.outputs.NonResourceAttributes nonResourceAttributes,
        @Nullable io.pulumi.kubernetes.authorization.v1.outputs.ResourceAttributes resourceAttributes) {
        this.nonResourceAttributes = nonResourceAttributes;
        this.resourceAttributes = resourceAttributes;
    }

    public Optional<io.pulumi.kubernetes.authorization.v1.outputs.NonResourceAttributes> getNonResourceAttributes() {
        return Optional.ofNullable(this.nonResourceAttributes);
    }
    public Optional<io.pulumi.kubernetes.authorization.v1.outputs.ResourceAttributes> getResourceAttributes() {
        return Optional.ofNullable(this.resourceAttributes);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SelfSubjectAccessReviewSpec defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable io.pulumi.kubernetes.authorization.v1.outputs.NonResourceAttributes nonResourceAttributes;
        private @Nullable io.pulumi.kubernetes.authorization.v1.outputs.ResourceAttributes resourceAttributes;

        public Builder() {
    	      // Empty
        }

        public Builder(SelfSubjectAccessReviewSpec defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.nonResourceAttributes = defaults.nonResourceAttributes;
    	      this.resourceAttributes = defaults.resourceAttributes;
        }

        public Builder setNonResourceAttributes(@Nullable io.pulumi.kubernetes.authorization.v1.outputs.NonResourceAttributes nonResourceAttributes) {
            this.nonResourceAttributes = nonResourceAttributes;
            return this;
        }

        public Builder setResourceAttributes(@Nullable io.pulumi.kubernetes.authorization.v1.outputs.ResourceAttributes resourceAttributes) {
            this.resourceAttributes = resourceAttributes;
            return this;
        }

        public SelfSubjectAccessReviewSpec build() {
            return new SelfSubjectAccessReviewSpec(nonResourceAttributes, resourceAttributes);
        }
    }
}
