// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.core.v1;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;
import io.pulumi.kubernetes.core.v1.inputs.*;

@ResourceType(type="kubernetes:core/v1:ReplicationController")
public class ReplicationController extends io.pulumi.kubernetes.KubernetesResource {
    @OutputExport(name="apiVersion", type=String.class, parameters={})
    private Output</* @Nullable */ String> apiVersion;

    public Output</* @Nullable */ String> getApiVersion() {
        return this.apiVersion;
    }
    @OutputExport(name="kind", type=String.class, parameters={})
    private Output</* @Nullable */ String> kind;

    public Output</* @Nullable */ String> getKind() {
        return this.kind;
    }
    @OutputExport(name="metadata", type=io.pulumi.kubernetes.meta.v1.outputs.ObjectMeta.class, parameters={})
    private Output</* @Nullable */ io.pulumi.kubernetes.meta.v1.outputs.ObjectMeta> metadata;

    public Output</* @Nullable */ io.pulumi.kubernetes.meta.v1.outputs.ObjectMeta> getMetadata() {
        return this.metadata;
    }
    @OutputExport(name="spec", type=io.pulumi.kubernetes.core.v1.outputs.ReplicationControllerSpec.class, parameters={})
    private Output</* @Nullable */ io.pulumi.kubernetes.core.v1.outputs.ReplicationControllerSpec> spec;

    public Output</* @Nullable */ io.pulumi.kubernetes.core.v1.outputs.ReplicationControllerSpec> getSpec() {
        return this.spec;
    }
    @OutputExport(name="status", type=io.pulumi.kubernetes.core.v1.outputs.ReplicationControllerStatus.class, parameters={})
    private Output</* @Nullable */ io.pulumi.kubernetes.core.v1.outputs.ReplicationControllerStatus> status;

    public Output</* @Nullable */ io.pulumi.kubernetes.core.v1.outputs.ReplicationControllerStatus> getStatus() {
        return this.status;
    }

    public ReplicationController(String name, @Nullable ReplicationControllerArgs args, @Nullable io.pulumi.resources.CustomResourceOptions options) {
        super("kubernetes:core/v1:ReplicationController", name, makeArgs(args), makeResourceOptions(options, Input.empty()));
    }

    private ReplicationController(String name, Input<String> id, @Nullable io.pulumi.resources.CustomResourceOptions options) {
        super("kubernetes:core/v1:ReplicationController", name, null, makeResourceOptions(options, id));
    }

    private static ReplicationControllerArgs makeArgs(@Nullable ReplicationControllerArgs args) {
        var builder = args == null ? ReplicationControllerArgs.builder() : ReplicationControllerArgs.builder(args);
        return builder
            .setApiVersion("v1")
            .setKind("ReplicationController")
            .build();
    }

    private static io.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable io.pulumi.resources.CustomResourceOptions options, @Nullable Input<String> id) {
        var defaultOptions = io.pulumi.resources.CustomResourceOptions.builder()
            .setVersion(Utilities.getVersion())
            .build();
        return io.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    public static ReplicationController get(String name, Input<String> id, @Nullable io.pulumi.resources.CustomResourceOptions options) {
        return new ReplicationController(name, id, options);
    }
}
