// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.apps.v1beta2.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class DeploymentSpec {
    private final @Nullable Integer minReadySeconds;
    private final @Nullable Boolean paused;
    private final @Nullable Integer progressDeadlineSeconds;
    private final @Nullable Integer replicas;
    private final @Nullable Integer revisionHistoryLimit;
    private final io.pulumi.kubernetes.meta.v1.outputs.LabelSelector selector;
    private final @Nullable io.pulumi.kubernetes.apps.v1beta2.outputs.DeploymentStrategy strategy;
    private final io.pulumi.kubernetes.core.v1.outputs.PodTemplateSpec template;

    @OutputCustomType.Constructor({"minReadySeconds","paused","progressDeadlineSeconds","replicas","revisionHistoryLimit","selector","strategy","template"})
    private DeploymentSpec(
        @Nullable Integer minReadySeconds,
        @Nullable Boolean paused,
        @Nullable Integer progressDeadlineSeconds,
        @Nullable Integer replicas,
        @Nullable Integer revisionHistoryLimit,
        io.pulumi.kubernetes.meta.v1.outputs.LabelSelector selector,
        @Nullable io.pulumi.kubernetes.apps.v1beta2.outputs.DeploymentStrategy strategy,
        io.pulumi.kubernetes.core.v1.outputs.PodTemplateSpec template) {
        this.minReadySeconds = minReadySeconds;
        this.paused = paused;
        this.progressDeadlineSeconds = progressDeadlineSeconds;
        this.replicas = replicas;
        this.revisionHistoryLimit = revisionHistoryLimit;
        this.selector = Objects.requireNonNull(selector);
        this.strategy = strategy;
        this.template = Objects.requireNonNull(template);
    }

    public Optional<Integer> getMinReadySeconds() {
        return Optional.ofNullable(this.minReadySeconds);
    }
    public Optional<Boolean> getPaused() {
        return Optional.ofNullable(this.paused);
    }
    public Optional<Integer> getProgressDeadlineSeconds() {
        return Optional.ofNullable(this.progressDeadlineSeconds);
    }
    public Optional<Integer> getReplicas() {
        return Optional.ofNullable(this.replicas);
    }
    public Optional<Integer> getRevisionHistoryLimit() {
        return Optional.ofNullable(this.revisionHistoryLimit);
    }
    public io.pulumi.kubernetes.meta.v1.outputs.LabelSelector getSelector() {
        return this.selector;
    }
    public Optional<io.pulumi.kubernetes.apps.v1beta2.outputs.DeploymentStrategy> getStrategy() {
        return Optional.ofNullable(this.strategy);
    }
    public io.pulumi.kubernetes.core.v1.outputs.PodTemplateSpec getTemplate() {
        return this.template;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DeploymentSpec defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable Integer minReadySeconds;
        private @Nullable Boolean paused;
        private @Nullable Integer progressDeadlineSeconds;
        private @Nullable Integer replicas;
        private @Nullable Integer revisionHistoryLimit;
        private io.pulumi.kubernetes.meta.v1.outputs.LabelSelector selector;
        private @Nullable io.pulumi.kubernetes.apps.v1beta2.outputs.DeploymentStrategy strategy;
        private io.pulumi.kubernetes.core.v1.outputs.PodTemplateSpec template;

        public Builder() {
    	      // Empty
        }

        public Builder(DeploymentSpec defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.minReadySeconds = defaults.minReadySeconds;
    	      this.paused = defaults.paused;
    	      this.progressDeadlineSeconds = defaults.progressDeadlineSeconds;
    	      this.replicas = defaults.replicas;
    	      this.revisionHistoryLimit = defaults.revisionHistoryLimit;
    	      this.selector = defaults.selector;
    	      this.strategy = defaults.strategy;
    	      this.template = defaults.template;
        }

        public Builder setMinReadySeconds(@Nullable Integer minReadySeconds) {
            this.minReadySeconds = minReadySeconds;
            return this;
        }

        public Builder setPaused(@Nullable Boolean paused) {
            this.paused = paused;
            return this;
        }

        public Builder setProgressDeadlineSeconds(@Nullable Integer progressDeadlineSeconds) {
            this.progressDeadlineSeconds = progressDeadlineSeconds;
            return this;
        }

        public Builder setReplicas(@Nullable Integer replicas) {
            this.replicas = replicas;
            return this;
        }

        public Builder setRevisionHistoryLimit(@Nullable Integer revisionHistoryLimit) {
            this.revisionHistoryLimit = revisionHistoryLimit;
            return this;
        }

        public Builder setSelector(io.pulumi.kubernetes.meta.v1.outputs.LabelSelector selector) {
            this.selector = Objects.requireNonNull(selector);
            return this;
        }

        public Builder setStrategy(@Nullable io.pulumi.kubernetes.apps.v1beta2.outputs.DeploymentStrategy strategy) {
            this.strategy = strategy;
            return this;
        }

        public Builder setTemplate(io.pulumi.kubernetes.core.v1.outputs.PodTemplateSpec template) {
            this.template = Objects.requireNonNull(template);
            return this;
        }

        public DeploymentSpec build() {
            return new DeploymentSpec(minReadySeconds, paused, progressDeadlineSeconds, replicas, revisionHistoryLimit, selector, strategy, template);
        }
    }
}
