// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.node.v1alpha1;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;
import io.pulumi.kubernetes.node.v1alpha1.inputs.*;

@ResourceType(type="kubernetes:node.k8s.io/v1alpha1:RuntimeClass")
public class RuntimeClass extends io.pulumi.kubernetes.KubernetesResource {
    @OutputExport(name="apiVersion", type=String.class, parameters={})
    private Output</* @Nullable */ String> apiVersion;

    public Output</* @Nullable */ String> getApiVersion() {
        return this.apiVersion;
    }
    @OutputExport(name="kind", type=String.class, parameters={})
    private Output</* @Nullable */ String> kind;

    public Output</* @Nullable */ String> getKind() {
        return this.kind;
    }
    @OutputExport(name="metadata", type=io.pulumi.kubernetes.meta.v1.outputs.ObjectMeta.class, parameters={})
    private Output</* @Nullable */ io.pulumi.kubernetes.meta.v1.outputs.ObjectMeta> metadata;

    public Output</* @Nullable */ io.pulumi.kubernetes.meta.v1.outputs.ObjectMeta> getMetadata() {
        return this.metadata;
    }
    @OutputExport(name="spec", type=io.pulumi.kubernetes.node.v1alpha1.outputs.RuntimeClassSpec.class, parameters={})
    private Output<io.pulumi.kubernetes.node.v1alpha1.outputs.RuntimeClassSpec> spec;

    public Output<io.pulumi.kubernetes.node.v1alpha1.outputs.RuntimeClassSpec> getSpec() {
        return this.spec;
    }

    public RuntimeClass(String name, RuntimeClassArgs args, @Nullable io.pulumi.resources.CustomResourceOptions options) {
        super("kubernetes:node.k8s.io/v1alpha1:RuntimeClass", name, makeArgs(args), makeResourceOptions(options, Input.empty()));
    }

    private RuntimeClass(String name, Input<String> id, @Nullable io.pulumi.resources.CustomResourceOptions options) {
        super("kubernetes:node.k8s.io/v1alpha1:RuntimeClass", name, null, makeResourceOptions(options, id));
    }

    private static RuntimeClassArgs makeArgs(RuntimeClassArgs args) {
        var builder = args == null ? RuntimeClassArgs.builder() : RuntimeClassArgs.builder(args);
        return builder
            .setApiVersion("node.k8s.io/v1alpha1")
            .setKind("RuntimeClass")
            .build();
    }

    private static io.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable io.pulumi.resources.CustomResourceOptions options, @Nullable Input<String> id) {
        var defaultOptions = io.pulumi.resources.CustomResourceOptions.builder()
            .setVersion(Utilities.getVersion())
            .setAliases(List.of(
                Input.of(Alias.builder().setType("kubernetes:node.k8s.io/v1:RuntimeClass").build()),
                Input.of(Alias.builder().setType("kubernetes:node.k8s.io/v1beta1:RuntimeClass").build())
            ))
            .build();
        return io.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    public static RuntimeClass get(String name, Input<String> id, @Nullable io.pulumi.resources.CustomResourceOptions options) {
        return new RuntimeClass(name, id, options);
    }
}
