// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.storage.v1.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class VolumeAttachmentSource {
    private final @Nullable io.pulumi.kubernetes.core.v1.outputs.PersistentVolumeSpec inlineVolumeSpec;
    private final @Nullable String persistentVolumeName;

    @OutputCustomType.Constructor({"inlineVolumeSpec","persistentVolumeName"})
    private VolumeAttachmentSource(
        @Nullable io.pulumi.kubernetes.core.v1.outputs.PersistentVolumeSpec inlineVolumeSpec,
        @Nullable String persistentVolumeName) {
        this.inlineVolumeSpec = inlineVolumeSpec;
        this.persistentVolumeName = persistentVolumeName;
    }

    public Optional<io.pulumi.kubernetes.core.v1.outputs.PersistentVolumeSpec> getInlineVolumeSpec() {
        return Optional.ofNullable(this.inlineVolumeSpec);
    }
    public Optional<String> getPersistentVolumeName() {
        return Optional.ofNullable(this.persistentVolumeName);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(VolumeAttachmentSource defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable io.pulumi.kubernetes.core.v1.outputs.PersistentVolumeSpec inlineVolumeSpec;
        private @Nullable String persistentVolumeName;

        public Builder() {
    	      // Empty
        }

        public Builder(VolumeAttachmentSource defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.inlineVolumeSpec = defaults.inlineVolumeSpec;
    	      this.persistentVolumeName = defaults.persistentVolumeName;
        }

        public Builder setInlineVolumeSpec(@Nullable io.pulumi.kubernetes.core.v1.outputs.PersistentVolumeSpec inlineVolumeSpec) {
            this.inlineVolumeSpec = inlineVolumeSpec;
            return this;
        }

        public Builder setPersistentVolumeName(@Nullable String persistentVolumeName) {
            this.persistentVolumeName = persistentVolumeName;
            return this;
        }

        public VolumeAttachmentSource build() {
            return new VolumeAttachmentSource(inlineVolumeSpec, persistentVolumeName);
        }
    }
}
