// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.core.v1.inputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;


public final class DownwardAPIVolumeFileArgs extends io.pulumi.resources.ResourceArgs {

    public static final DownwardAPIVolumeFileArgs Empty = new DownwardAPIVolumeFileArgs();

    @InputImport(name="fieldRef")
    private final @Nullable Input<io.pulumi.kubernetes.core.v1.inputs.ObjectFieldSelectorArgs> fieldRef;

    public Input<io.pulumi.kubernetes.core.v1.inputs.ObjectFieldSelectorArgs> getFieldRef() {
        return this.fieldRef == null ? Input.empty() : this.fieldRef;
    }

    @InputImport(name="mode")
    private final @Nullable Input<Integer> mode;

    public Input<Integer> getMode() {
        return this.mode == null ? Input.empty() : this.mode;
    }

    @InputImport(name="path", required=true)
    private final Input<String> path;

    public Input<String> getPath() {
        return this.path;
    }

    @InputImport(name="resourceFieldRef")
    private final @Nullable Input<io.pulumi.kubernetes.core.v1.inputs.ResourceFieldSelectorArgs> resourceFieldRef;

    public Input<io.pulumi.kubernetes.core.v1.inputs.ResourceFieldSelectorArgs> getResourceFieldRef() {
        return this.resourceFieldRef == null ? Input.empty() : this.resourceFieldRef;
    }

    public DownwardAPIVolumeFileArgs(
        @Nullable Input<io.pulumi.kubernetes.core.v1.inputs.ObjectFieldSelectorArgs> fieldRef,
        @Nullable Input<Integer> mode,
        Input<String> path,
        @Nullable Input<io.pulumi.kubernetes.core.v1.inputs.ResourceFieldSelectorArgs> resourceFieldRef) {
        this.fieldRef = fieldRef;
        this.mode = mode;
        this.path = Objects.requireNonNull(path, "expected parameter 'path' to be non-null");
        this.resourceFieldRef = resourceFieldRef;
    }

    private DownwardAPIVolumeFileArgs() {
        this.fieldRef = Input.empty();
        this.mode = Input.empty();
        this.path = Input.empty();
        this.resourceFieldRef = Input.empty();
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DownwardAPIVolumeFileArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable Input<io.pulumi.kubernetes.core.v1.inputs.ObjectFieldSelectorArgs> fieldRef;
        private @Nullable Input<Integer> mode;
        private Input<String> path;
        private @Nullable Input<io.pulumi.kubernetes.core.v1.inputs.ResourceFieldSelectorArgs> resourceFieldRef;

        public Builder() {
    	      // Empty
        }

        public Builder(DownwardAPIVolumeFileArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.fieldRef = defaults.fieldRef;
    	      this.mode = defaults.mode;
    	      this.path = defaults.path;
    	      this.resourceFieldRef = defaults.resourceFieldRef;
        }

        public Builder setFieldRef(@Nullable Input<io.pulumi.kubernetes.core.v1.inputs.ObjectFieldSelectorArgs> fieldRef) {
            this.fieldRef = fieldRef;
            return this;
        }

        public Builder setFieldRef(@Nullable io.pulumi.kubernetes.core.v1.inputs.ObjectFieldSelectorArgs fieldRef) {
            this.fieldRef = Input.ofNullable(fieldRef);
            return this;
        }

        public Builder setMode(@Nullable Input<Integer> mode) {
            this.mode = mode;
            return this;
        }

        public Builder setMode(@Nullable Integer mode) {
            this.mode = Input.ofNullable(mode);
            return this;
        }

        public Builder setPath(Input<String> path) {
            this.path = Objects.requireNonNull(path);
            return this;
        }

        public Builder setPath(String path) {
            this.path = Input.of(Objects.requireNonNull(path));
            return this;
        }

        public Builder setResourceFieldRef(@Nullable Input<io.pulumi.kubernetes.core.v1.inputs.ResourceFieldSelectorArgs> resourceFieldRef) {
            this.resourceFieldRef = resourceFieldRef;
            return this;
        }

        public Builder setResourceFieldRef(@Nullable io.pulumi.kubernetes.core.v1.inputs.ResourceFieldSelectorArgs resourceFieldRef) {
            this.resourceFieldRef = Input.ofNullable(resourceFieldRef);
            return this;
        }

        public DownwardAPIVolumeFileArgs build() {
            return new DownwardAPIVolumeFileArgs(fieldRef, mode, path, resourceFieldRef);
        }
    }
}
