// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.core.v1.inputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;


public final class DownwardAPIVolumeSourceArgs extends io.pulumi.resources.ResourceArgs {

    public static final DownwardAPIVolumeSourceArgs Empty = new DownwardAPIVolumeSourceArgs();

    @InputImport(name="defaultMode")
    private final @Nullable Input<Integer> defaultMode;

    public Input<Integer> getDefaultMode() {
        return this.defaultMode == null ? Input.empty() : this.defaultMode;
    }

    @InputImport(name="items")
    private final @Nullable Input<List<io.pulumi.kubernetes.core.v1.inputs.DownwardAPIVolumeFileArgs>> items;

    public Input<List<io.pulumi.kubernetes.core.v1.inputs.DownwardAPIVolumeFileArgs>> getItems() {
        return this.items == null ? Input.empty() : this.items;
    }

    public DownwardAPIVolumeSourceArgs(
        @Nullable Input<Integer> defaultMode,
        @Nullable Input<List<io.pulumi.kubernetes.core.v1.inputs.DownwardAPIVolumeFileArgs>> items) {
        this.defaultMode = defaultMode;
        this.items = items;
    }

    private DownwardAPIVolumeSourceArgs() {
        this.defaultMode = Input.empty();
        this.items = Input.empty();
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DownwardAPIVolumeSourceArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable Input<Integer> defaultMode;
        private @Nullable Input<List<io.pulumi.kubernetes.core.v1.inputs.DownwardAPIVolumeFileArgs>> items;

        public Builder() {
    	      // Empty
        }

        public Builder(DownwardAPIVolumeSourceArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.defaultMode = defaults.defaultMode;
    	      this.items = defaults.items;
        }

        public Builder setDefaultMode(@Nullable Input<Integer> defaultMode) {
            this.defaultMode = defaultMode;
            return this;
        }

        public Builder setDefaultMode(@Nullable Integer defaultMode) {
            this.defaultMode = Input.ofNullable(defaultMode);
            return this;
        }

        public Builder setItems(@Nullable Input<List<io.pulumi.kubernetes.core.v1.inputs.DownwardAPIVolumeFileArgs>> items) {
            this.items = items;
            return this;
        }

        public Builder setItems(@Nullable List<io.pulumi.kubernetes.core.v1.inputs.DownwardAPIVolumeFileArgs> items) {
            this.items = Input.ofNullable(items);
            return this;
        }

        public DownwardAPIVolumeSourceArgs build() {
            return new DownwardAPIVolumeSourceArgs(defaultMode, items);
        }
    }
}
