// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.core.v1.inputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;


public final class GlusterfsVolumeSourceArgs extends io.pulumi.resources.ResourceArgs {

    public static final GlusterfsVolumeSourceArgs Empty = new GlusterfsVolumeSourceArgs();

    @InputImport(name="endpoints", required=true)
    private final Input<String> endpoints;

    public Input<String> getEndpoints() {
        return this.endpoints;
    }

    @InputImport(name="path", required=true)
    private final Input<String> path;

    public Input<String> getPath() {
        return this.path;
    }

    @InputImport(name="readOnly")
    private final @Nullable Input<Boolean> readOnly;

    public Input<Boolean> getReadOnly() {
        return this.readOnly == null ? Input.empty() : this.readOnly;
    }

    public GlusterfsVolumeSourceArgs(
        Input<String> endpoints,
        Input<String> path,
        @Nullable Input<Boolean> readOnly) {
        this.endpoints = Objects.requireNonNull(endpoints, "expected parameter 'endpoints' to be non-null");
        this.path = Objects.requireNonNull(path, "expected parameter 'path' to be non-null");
        this.readOnly = readOnly;
    }

    private GlusterfsVolumeSourceArgs() {
        this.endpoints = Input.empty();
        this.path = Input.empty();
        this.readOnly = Input.empty();
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GlusterfsVolumeSourceArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private Input<String> endpoints;
        private Input<String> path;
        private @Nullable Input<Boolean> readOnly;

        public Builder() {
    	      // Empty
        }

        public Builder(GlusterfsVolumeSourceArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.endpoints = defaults.endpoints;
    	      this.path = defaults.path;
    	      this.readOnly = defaults.readOnly;
        }

        public Builder setEndpoints(Input<String> endpoints) {
            this.endpoints = Objects.requireNonNull(endpoints);
            return this;
        }

        public Builder setEndpoints(String endpoints) {
            this.endpoints = Input.of(Objects.requireNonNull(endpoints));
            return this;
        }

        public Builder setPath(Input<String> path) {
            this.path = Objects.requireNonNull(path);
            return this;
        }

        public Builder setPath(String path) {
            this.path = Input.of(Objects.requireNonNull(path));
            return this;
        }

        public Builder setReadOnly(@Nullable Input<Boolean> readOnly) {
            this.readOnly = readOnly;
            return this;
        }

        public Builder setReadOnly(@Nullable Boolean readOnly) {
            this.readOnly = Input.ofNullable(readOnly);
            return this;
        }

        public GlusterfsVolumeSourceArgs build() {
            return new GlusterfsVolumeSourceArgs(endpoints, path, readOnly);
        }
    }
}
