// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.core.v1.inputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;


public final class HandlerArgs extends io.pulumi.resources.ResourceArgs {

    public static final HandlerArgs Empty = new HandlerArgs();

    @InputImport(name="exec")
    private final @Nullable Input<io.pulumi.kubernetes.core.v1.inputs.ExecActionArgs> exec;

    public Input<io.pulumi.kubernetes.core.v1.inputs.ExecActionArgs> getExec() {
        return this.exec == null ? Input.empty() : this.exec;
    }

    @InputImport(name="httpGet")
    private final @Nullable Input<io.pulumi.kubernetes.core.v1.inputs.HTTPGetActionArgs> httpGet;

    public Input<io.pulumi.kubernetes.core.v1.inputs.HTTPGetActionArgs> getHttpGet() {
        return this.httpGet == null ? Input.empty() : this.httpGet;
    }

    @InputImport(name="tcpSocket")
    private final @Nullable Input<io.pulumi.kubernetes.core.v1.inputs.TCPSocketActionArgs> tcpSocket;

    public Input<io.pulumi.kubernetes.core.v1.inputs.TCPSocketActionArgs> getTcpSocket() {
        return this.tcpSocket == null ? Input.empty() : this.tcpSocket;
    }

    public HandlerArgs(
        @Nullable Input<io.pulumi.kubernetes.core.v1.inputs.ExecActionArgs> exec,
        @Nullable Input<io.pulumi.kubernetes.core.v1.inputs.HTTPGetActionArgs> httpGet,
        @Nullable Input<io.pulumi.kubernetes.core.v1.inputs.TCPSocketActionArgs> tcpSocket) {
        this.exec = exec;
        this.httpGet = httpGet;
        this.tcpSocket = tcpSocket;
    }

    private HandlerArgs() {
        this.exec = Input.empty();
        this.httpGet = Input.empty();
        this.tcpSocket = Input.empty();
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(HandlerArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable Input<io.pulumi.kubernetes.core.v1.inputs.ExecActionArgs> exec;
        private @Nullable Input<io.pulumi.kubernetes.core.v1.inputs.HTTPGetActionArgs> httpGet;
        private @Nullable Input<io.pulumi.kubernetes.core.v1.inputs.TCPSocketActionArgs> tcpSocket;

        public Builder() {
    	      // Empty
        }

        public Builder(HandlerArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.exec = defaults.exec;
    	      this.httpGet = defaults.httpGet;
    	      this.tcpSocket = defaults.tcpSocket;
        }

        public Builder setExec(@Nullable Input<io.pulumi.kubernetes.core.v1.inputs.ExecActionArgs> exec) {
            this.exec = exec;
            return this;
        }

        public Builder setExec(@Nullable io.pulumi.kubernetes.core.v1.inputs.ExecActionArgs exec) {
            this.exec = Input.ofNullable(exec);
            return this;
        }

        public Builder setHttpGet(@Nullable Input<io.pulumi.kubernetes.core.v1.inputs.HTTPGetActionArgs> httpGet) {
            this.httpGet = httpGet;
            return this;
        }

        public Builder setHttpGet(@Nullable io.pulumi.kubernetes.core.v1.inputs.HTTPGetActionArgs httpGet) {
            this.httpGet = Input.ofNullable(httpGet);
            return this;
        }

        public Builder setTcpSocket(@Nullable Input<io.pulumi.kubernetes.core.v1.inputs.TCPSocketActionArgs> tcpSocket) {
            this.tcpSocket = tcpSocket;
            return this;
        }

        public Builder setTcpSocket(@Nullable io.pulumi.kubernetes.core.v1.inputs.TCPSocketActionArgs tcpSocket) {
            this.tcpSocket = Input.ofNullable(tcpSocket);
            return this;
        }

        public HandlerArgs build() {
            return new HandlerArgs(exec, httpGet, tcpSocket);
        }
    }
}
