// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.core.v1.inputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;


public final class LoadBalancerStatusArgs extends io.pulumi.resources.ResourceArgs {

    public static final LoadBalancerStatusArgs Empty = new LoadBalancerStatusArgs();

    @InputImport(name="ingress")
    private final @Nullable Input<List<io.pulumi.kubernetes.core.v1.inputs.LoadBalancerIngressArgs>> ingress;

    public Input<List<io.pulumi.kubernetes.core.v1.inputs.LoadBalancerIngressArgs>> getIngress() {
        return this.ingress == null ? Input.empty() : this.ingress;
    }

    public LoadBalancerStatusArgs(@Nullable Input<List<io.pulumi.kubernetes.core.v1.inputs.LoadBalancerIngressArgs>> ingress) {
        this.ingress = ingress;
    }

    private LoadBalancerStatusArgs() {
        this.ingress = Input.empty();
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(LoadBalancerStatusArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable Input<List<io.pulumi.kubernetes.core.v1.inputs.LoadBalancerIngressArgs>> ingress;

        public Builder() {
    	      // Empty
        }

        public Builder(LoadBalancerStatusArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.ingress = defaults.ingress;
        }

        public Builder setIngress(@Nullable Input<List<io.pulumi.kubernetes.core.v1.inputs.LoadBalancerIngressArgs>> ingress) {
            this.ingress = ingress;
            return this;
        }

        public Builder setIngress(@Nullable List<io.pulumi.kubernetes.core.v1.inputs.LoadBalancerIngressArgs> ingress) {
            this.ingress = Input.ofNullable(ingress);
            return this;
        }

        public LoadBalancerStatusArgs build() {
            return new LoadBalancerStatusArgs(ingress);
        }
    }
}
