// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.core.v1.inputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;


public final class NFSVolumeSourceArgs extends io.pulumi.resources.ResourceArgs {

    public static final NFSVolumeSourceArgs Empty = new NFSVolumeSourceArgs();

    @InputImport(name="path", required=true)
    private final Input<String> path;

    public Input<String> getPath() {
        return this.path;
    }

    @InputImport(name="readOnly")
    private final @Nullable Input<Boolean> readOnly;

    public Input<Boolean> getReadOnly() {
        return this.readOnly == null ? Input.empty() : this.readOnly;
    }

    @InputImport(name="server", required=true)
    private final Input<String> server;

    public Input<String> getServer() {
        return this.server;
    }

    public NFSVolumeSourceArgs(
        Input<String> path,
        @Nullable Input<Boolean> readOnly,
        Input<String> server) {
        this.path = Objects.requireNonNull(path, "expected parameter 'path' to be non-null");
        this.readOnly = readOnly;
        this.server = Objects.requireNonNull(server, "expected parameter 'server' to be non-null");
    }

    private NFSVolumeSourceArgs() {
        this.path = Input.empty();
        this.readOnly = Input.empty();
        this.server = Input.empty();
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NFSVolumeSourceArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private Input<String> path;
        private @Nullable Input<Boolean> readOnly;
        private Input<String> server;

        public Builder() {
    	      // Empty
        }

        public Builder(NFSVolumeSourceArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.path = defaults.path;
    	      this.readOnly = defaults.readOnly;
    	      this.server = defaults.server;
        }

        public Builder setPath(Input<String> path) {
            this.path = Objects.requireNonNull(path);
            return this;
        }

        public Builder setPath(String path) {
            this.path = Input.of(Objects.requireNonNull(path));
            return this;
        }

        public Builder setReadOnly(@Nullable Input<Boolean> readOnly) {
            this.readOnly = readOnly;
            return this;
        }

        public Builder setReadOnly(@Nullable Boolean readOnly) {
            this.readOnly = Input.ofNullable(readOnly);
            return this;
        }

        public Builder setServer(Input<String> server) {
            this.server = Objects.requireNonNull(server);
            return this;
        }

        public Builder setServer(String server) {
            this.server = Input.of(Objects.requireNonNull(server));
            return this;
        }

        public NFSVolumeSourceArgs build() {
            return new NFSVolumeSourceArgs(path, readOnly, server);
        }
    }
}
