// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.core.v1.inputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;


public final class NodeStatusArgs extends io.pulumi.resources.ResourceArgs {

    public static final NodeStatusArgs Empty = new NodeStatusArgs();

    @InputImport(name="addresses")
    private final @Nullable Input<List<io.pulumi.kubernetes.core.v1.inputs.NodeAddressArgs>> addresses;

    public Input<List<io.pulumi.kubernetes.core.v1.inputs.NodeAddressArgs>> getAddresses() {
        return this.addresses == null ? Input.empty() : this.addresses;
    }

    @InputImport(name="allocatable")
    private final @Nullable Input<Map<String,String>> allocatable;

    public Input<Map<String,String>> getAllocatable() {
        return this.allocatable == null ? Input.empty() : this.allocatable;
    }

    @InputImport(name="capacity")
    private final @Nullable Input<Map<String,String>> capacity;

    public Input<Map<String,String>> getCapacity() {
        return this.capacity == null ? Input.empty() : this.capacity;
    }

    @InputImport(name="conditions")
    private final @Nullable Input<List<io.pulumi.kubernetes.core.v1.inputs.NodeConditionArgs>> conditions;

    public Input<List<io.pulumi.kubernetes.core.v1.inputs.NodeConditionArgs>> getConditions() {
        return this.conditions == null ? Input.empty() : this.conditions;
    }

    @InputImport(name="config")
    private final @Nullable Input<io.pulumi.kubernetes.core.v1.inputs.NodeConfigStatusArgs> config;

    public Input<io.pulumi.kubernetes.core.v1.inputs.NodeConfigStatusArgs> getConfig() {
        return this.config == null ? Input.empty() : this.config;
    }

    @InputImport(name="daemonEndpoints")
    private final @Nullable Input<io.pulumi.kubernetes.core.v1.inputs.NodeDaemonEndpointsArgs> daemonEndpoints;

    public Input<io.pulumi.kubernetes.core.v1.inputs.NodeDaemonEndpointsArgs> getDaemonEndpoints() {
        return this.daemonEndpoints == null ? Input.empty() : this.daemonEndpoints;
    }

    @InputImport(name="images")
    private final @Nullable Input<List<io.pulumi.kubernetes.core.v1.inputs.ContainerImageArgs>> images;

    public Input<List<io.pulumi.kubernetes.core.v1.inputs.ContainerImageArgs>> getImages() {
        return this.images == null ? Input.empty() : this.images;
    }

    @InputImport(name="nodeInfo")
    private final @Nullable Input<io.pulumi.kubernetes.core.v1.inputs.NodeSystemInfoArgs> nodeInfo;

    public Input<io.pulumi.kubernetes.core.v1.inputs.NodeSystemInfoArgs> getNodeInfo() {
        return this.nodeInfo == null ? Input.empty() : this.nodeInfo;
    }

    @InputImport(name="phase")
    private final @Nullable Input<String> phase;

    public Input<String> getPhase() {
        return this.phase == null ? Input.empty() : this.phase;
    }

    @InputImport(name="volumesAttached")
    private final @Nullable Input<List<io.pulumi.kubernetes.core.v1.inputs.AttachedVolumeArgs>> volumesAttached;

    public Input<List<io.pulumi.kubernetes.core.v1.inputs.AttachedVolumeArgs>> getVolumesAttached() {
        return this.volumesAttached == null ? Input.empty() : this.volumesAttached;
    }

    @InputImport(name="volumesInUse")
    private final @Nullable Input<List<String>> volumesInUse;

    public Input<List<String>> getVolumesInUse() {
        return this.volumesInUse == null ? Input.empty() : this.volumesInUse;
    }

    public NodeStatusArgs(
        @Nullable Input<List<io.pulumi.kubernetes.core.v1.inputs.NodeAddressArgs>> addresses,
        @Nullable Input<Map<String,String>> allocatable,
        @Nullable Input<Map<String,String>> capacity,
        @Nullable Input<List<io.pulumi.kubernetes.core.v1.inputs.NodeConditionArgs>> conditions,
        @Nullable Input<io.pulumi.kubernetes.core.v1.inputs.NodeConfigStatusArgs> config,
        @Nullable Input<io.pulumi.kubernetes.core.v1.inputs.NodeDaemonEndpointsArgs> daemonEndpoints,
        @Nullable Input<List<io.pulumi.kubernetes.core.v1.inputs.ContainerImageArgs>> images,
        @Nullable Input<io.pulumi.kubernetes.core.v1.inputs.NodeSystemInfoArgs> nodeInfo,
        @Nullable Input<String> phase,
        @Nullable Input<List<io.pulumi.kubernetes.core.v1.inputs.AttachedVolumeArgs>> volumesAttached,
        @Nullable Input<List<String>> volumesInUse) {
        this.addresses = addresses;
        this.allocatable = allocatable;
        this.capacity = capacity;
        this.conditions = conditions;
        this.config = config;
        this.daemonEndpoints = daemonEndpoints;
        this.images = images;
        this.nodeInfo = nodeInfo;
        this.phase = phase;
        this.volumesAttached = volumesAttached;
        this.volumesInUse = volumesInUse;
    }

    private NodeStatusArgs() {
        this.addresses = Input.empty();
        this.allocatable = Input.empty();
        this.capacity = Input.empty();
        this.conditions = Input.empty();
        this.config = Input.empty();
        this.daemonEndpoints = Input.empty();
        this.images = Input.empty();
        this.nodeInfo = Input.empty();
        this.phase = Input.empty();
        this.volumesAttached = Input.empty();
        this.volumesInUse = Input.empty();
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NodeStatusArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable Input<List<io.pulumi.kubernetes.core.v1.inputs.NodeAddressArgs>> addresses;
        private @Nullable Input<Map<String,String>> allocatable;
        private @Nullable Input<Map<String,String>> capacity;
        private @Nullable Input<List<io.pulumi.kubernetes.core.v1.inputs.NodeConditionArgs>> conditions;
        private @Nullable Input<io.pulumi.kubernetes.core.v1.inputs.NodeConfigStatusArgs> config;
        private @Nullable Input<io.pulumi.kubernetes.core.v1.inputs.NodeDaemonEndpointsArgs> daemonEndpoints;
        private @Nullable Input<List<io.pulumi.kubernetes.core.v1.inputs.ContainerImageArgs>> images;
        private @Nullable Input<io.pulumi.kubernetes.core.v1.inputs.NodeSystemInfoArgs> nodeInfo;
        private @Nullable Input<String> phase;
        private @Nullable Input<List<io.pulumi.kubernetes.core.v1.inputs.AttachedVolumeArgs>> volumesAttached;
        private @Nullable Input<List<String>> volumesInUse;

        public Builder() {
    	      // Empty
        }

        public Builder(NodeStatusArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.addresses = defaults.addresses;
    	      this.allocatable = defaults.allocatable;
    	      this.capacity = defaults.capacity;
    	      this.conditions = defaults.conditions;
    	      this.config = defaults.config;
    	      this.daemonEndpoints = defaults.daemonEndpoints;
    	      this.images = defaults.images;
    	      this.nodeInfo = defaults.nodeInfo;
    	      this.phase = defaults.phase;
    	      this.volumesAttached = defaults.volumesAttached;
    	      this.volumesInUse = defaults.volumesInUse;
        }

        public Builder setAddresses(@Nullable Input<List<io.pulumi.kubernetes.core.v1.inputs.NodeAddressArgs>> addresses) {
            this.addresses = addresses;
            return this;
        }

        public Builder setAddresses(@Nullable List<io.pulumi.kubernetes.core.v1.inputs.NodeAddressArgs> addresses) {
            this.addresses = Input.ofNullable(addresses);
            return this;
        }

        public Builder setAllocatable(@Nullable Input<Map<String,String>> allocatable) {
            this.allocatable = allocatable;
            return this;
        }

        public Builder setAllocatable(@Nullable Map<String,String> allocatable) {
            this.allocatable = Input.ofNullable(allocatable);
            return this;
        }

        public Builder setCapacity(@Nullable Input<Map<String,String>> capacity) {
            this.capacity = capacity;
            return this;
        }

        public Builder setCapacity(@Nullable Map<String,String> capacity) {
            this.capacity = Input.ofNullable(capacity);
            return this;
        }

        public Builder setConditions(@Nullable Input<List<io.pulumi.kubernetes.core.v1.inputs.NodeConditionArgs>> conditions) {
            this.conditions = conditions;
            return this;
        }

        public Builder setConditions(@Nullable List<io.pulumi.kubernetes.core.v1.inputs.NodeConditionArgs> conditions) {
            this.conditions = Input.ofNullable(conditions);
            return this;
        }

        public Builder setConfig(@Nullable Input<io.pulumi.kubernetes.core.v1.inputs.NodeConfigStatusArgs> config) {
            this.config = config;
            return this;
        }

        public Builder setConfig(@Nullable io.pulumi.kubernetes.core.v1.inputs.NodeConfigStatusArgs config) {
            this.config = Input.ofNullable(config);
            return this;
        }

        public Builder setDaemonEndpoints(@Nullable Input<io.pulumi.kubernetes.core.v1.inputs.NodeDaemonEndpointsArgs> daemonEndpoints) {
            this.daemonEndpoints = daemonEndpoints;
            return this;
        }

        public Builder setDaemonEndpoints(@Nullable io.pulumi.kubernetes.core.v1.inputs.NodeDaemonEndpointsArgs daemonEndpoints) {
            this.daemonEndpoints = Input.ofNullable(daemonEndpoints);
            return this;
        }

        public Builder setImages(@Nullable Input<List<io.pulumi.kubernetes.core.v1.inputs.ContainerImageArgs>> images) {
            this.images = images;
            return this;
        }

        public Builder setImages(@Nullable List<io.pulumi.kubernetes.core.v1.inputs.ContainerImageArgs> images) {
            this.images = Input.ofNullable(images);
            return this;
        }

        public Builder setNodeInfo(@Nullable Input<io.pulumi.kubernetes.core.v1.inputs.NodeSystemInfoArgs> nodeInfo) {
            this.nodeInfo = nodeInfo;
            return this;
        }

        public Builder setNodeInfo(@Nullable io.pulumi.kubernetes.core.v1.inputs.NodeSystemInfoArgs nodeInfo) {
            this.nodeInfo = Input.ofNullable(nodeInfo);
            return this;
        }

        public Builder setPhase(@Nullable Input<String> phase) {
            this.phase = phase;
            return this;
        }

        public Builder setPhase(@Nullable String phase) {
            this.phase = Input.ofNullable(phase);
            return this;
        }

        public Builder setVolumesAttached(@Nullable Input<List<io.pulumi.kubernetes.core.v1.inputs.AttachedVolumeArgs>> volumesAttached) {
            this.volumesAttached = volumesAttached;
            return this;
        }

        public Builder setVolumesAttached(@Nullable List<io.pulumi.kubernetes.core.v1.inputs.AttachedVolumeArgs> volumesAttached) {
            this.volumesAttached = Input.ofNullable(volumesAttached);
            return this;
        }

        public Builder setVolumesInUse(@Nullable Input<List<String>> volumesInUse) {
            this.volumesInUse = volumesInUse;
            return this;
        }

        public Builder setVolumesInUse(@Nullable List<String> volumesInUse) {
            this.volumesInUse = Input.ofNullable(volumesInUse);
            return this;
        }

        public NodeStatusArgs build() {
            return new NodeStatusArgs(addresses, allocatable, capacity, conditions, config, daemonEndpoints, images, nodeInfo, phase, volumesAttached, volumesInUse);
        }
    }
}
