// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.core.v1.inputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;


public final class PodDNSConfigArgs extends io.pulumi.resources.ResourceArgs {

    public static final PodDNSConfigArgs Empty = new PodDNSConfigArgs();

    @InputImport(name="nameservers")
    private final @Nullable Input<List<String>> nameservers;

    public Input<List<String>> getNameservers() {
        return this.nameservers == null ? Input.empty() : this.nameservers;
    }

    @InputImport(name="options")
    private final @Nullable Input<List<io.pulumi.kubernetes.core.v1.inputs.PodDNSConfigOptionArgs>> options;

    public Input<List<io.pulumi.kubernetes.core.v1.inputs.PodDNSConfigOptionArgs>> getOptions() {
        return this.options == null ? Input.empty() : this.options;
    }

    @InputImport(name="searches")
    private final @Nullable Input<List<String>> searches;

    public Input<List<String>> getSearches() {
        return this.searches == null ? Input.empty() : this.searches;
    }

    public PodDNSConfigArgs(
        @Nullable Input<List<String>> nameservers,
        @Nullable Input<List<io.pulumi.kubernetes.core.v1.inputs.PodDNSConfigOptionArgs>> options,
        @Nullable Input<List<String>> searches) {
        this.nameservers = nameservers;
        this.options = options;
        this.searches = searches;
    }

    private PodDNSConfigArgs() {
        this.nameservers = Input.empty();
        this.options = Input.empty();
        this.searches = Input.empty();
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(PodDNSConfigArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable Input<List<String>> nameservers;
        private @Nullable Input<List<io.pulumi.kubernetes.core.v1.inputs.PodDNSConfigOptionArgs>> options;
        private @Nullable Input<List<String>> searches;

        public Builder() {
    	      // Empty
        }

        public Builder(PodDNSConfigArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.nameservers = defaults.nameservers;
    	      this.options = defaults.options;
    	      this.searches = defaults.searches;
        }

        public Builder setNameservers(@Nullable Input<List<String>> nameservers) {
            this.nameservers = nameservers;
            return this;
        }

        public Builder setNameservers(@Nullable List<String> nameservers) {
            this.nameservers = Input.ofNullable(nameservers);
            return this;
        }

        public Builder setOptions(@Nullable Input<List<io.pulumi.kubernetes.core.v1.inputs.PodDNSConfigOptionArgs>> options) {
            this.options = options;
            return this;
        }

        public Builder setOptions(@Nullable List<io.pulumi.kubernetes.core.v1.inputs.PodDNSConfigOptionArgs> options) {
            this.options = Input.ofNullable(options);
            return this;
        }

        public Builder setSearches(@Nullable Input<List<String>> searches) {
            this.searches = searches;
            return this;
        }

        public Builder setSearches(@Nullable List<String> searches) {
            this.searches = Input.ofNullable(searches);
            return this;
        }

        public PodDNSConfigArgs build() {
            return new PodDNSConfigArgs(nameservers, options, searches);
        }
    }
}
