// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.autoscaling.v2beta2.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class HPAScalingRules {
    private final @Nullable List<io.pulumi.kubernetes.autoscaling.v2beta2.outputs.HPAScalingPolicy> policies;
    private final @Nullable String selectPolicy;
    private final @Nullable Integer stabilizationWindowSeconds;

    @OutputCustomType.Constructor({"policies","selectPolicy","stabilizationWindowSeconds"})
    private HPAScalingRules(
        @Nullable List<io.pulumi.kubernetes.autoscaling.v2beta2.outputs.HPAScalingPolicy> policies,
        @Nullable String selectPolicy,
        @Nullable Integer stabilizationWindowSeconds) {
        this.policies = policies;
        this.selectPolicy = selectPolicy;
        this.stabilizationWindowSeconds = stabilizationWindowSeconds;
    }

    public List<io.pulumi.kubernetes.autoscaling.v2beta2.outputs.HPAScalingPolicy> getPolicies() {
        return this.policies == null ? List.of() : this.policies;
    }
    public Optional<String> getSelectPolicy() {
        return Optional.ofNullable(this.selectPolicy);
    }
    public Optional<Integer> getStabilizationWindowSeconds() {
        return Optional.ofNullable(this.stabilizationWindowSeconds);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(HPAScalingRules defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable List<io.pulumi.kubernetes.autoscaling.v2beta2.outputs.HPAScalingPolicy> policies;
        private @Nullable String selectPolicy;
        private @Nullable Integer stabilizationWindowSeconds;

        public Builder() {
    	      // Empty
        }

        public Builder(HPAScalingRules defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.policies = defaults.policies;
    	      this.selectPolicy = defaults.selectPolicy;
    	      this.stabilizationWindowSeconds = defaults.stabilizationWindowSeconds;
        }

        public Builder setPolicies(@Nullable List<io.pulumi.kubernetes.autoscaling.v2beta2.outputs.HPAScalingPolicy> policies) {
            this.policies = policies;
            return this;
        }

        public Builder setSelectPolicy(@Nullable String selectPolicy) {
            this.selectPolicy = selectPolicy;
            return this;
        }

        public Builder setStabilizationWindowSeconds(@Nullable Integer stabilizationWindowSeconds) {
            this.stabilizationWindowSeconds = stabilizationWindowSeconds;
            return this;
        }

        public HPAScalingRules build() {
            return new HPAScalingRules(policies, selectPolicy, stabilizationWindowSeconds);
        }
    }
}
