// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.autoscaling.v2beta2.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class PodsMetricStatus {
    private final io.pulumi.kubernetes.autoscaling.v2beta2.outputs.MetricValueStatus current;
    private final io.pulumi.kubernetes.autoscaling.v2beta2.outputs.MetricIdentifier metric;

    @OutputCustomType.Constructor({"current","metric"})
    private PodsMetricStatus(
        io.pulumi.kubernetes.autoscaling.v2beta2.outputs.MetricValueStatus current,
        io.pulumi.kubernetes.autoscaling.v2beta2.outputs.MetricIdentifier metric) {
        this.current = Objects.requireNonNull(current);
        this.metric = Objects.requireNonNull(metric);
    }

    public io.pulumi.kubernetes.autoscaling.v2beta2.outputs.MetricValueStatus getCurrent() {
        return this.current;
    }
    public io.pulumi.kubernetes.autoscaling.v2beta2.outputs.MetricIdentifier getMetric() {
        return this.metric;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(PodsMetricStatus defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private io.pulumi.kubernetes.autoscaling.v2beta2.outputs.MetricValueStatus current;
        private io.pulumi.kubernetes.autoscaling.v2beta2.outputs.MetricIdentifier metric;

        public Builder() {
    	      // Empty
        }

        public Builder(PodsMetricStatus defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.current = defaults.current;
    	      this.metric = defaults.metric;
        }

        public Builder setCurrent(io.pulumi.kubernetes.autoscaling.v2beta2.outputs.MetricValueStatus current) {
            this.current = Objects.requireNonNull(current);
            return this;
        }

        public Builder setMetric(io.pulumi.kubernetes.autoscaling.v2beta2.outputs.MetricIdentifier metric) {
            this.metric = Objects.requireNonNull(metric);
            return this;
        }

        public PodsMetricStatus build() {
            return new PodsMetricStatus(current, metric);
        }
    }
}
