// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.autoscaling.v2beta2.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class ResourceMetricSource {
    private final String name;
    private final io.pulumi.kubernetes.autoscaling.v2beta2.outputs.MetricTarget target;

    @OutputCustomType.Constructor({"name","target"})
    private ResourceMetricSource(
        String name,
        io.pulumi.kubernetes.autoscaling.v2beta2.outputs.MetricTarget target) {
        this.name = Objects.requireNonNull(name);
        this.target = Objects.requireNonNull(target);
    }

    public String getName() {
        return this.name;
    }
    public io.pulumi.kubernetes.autoscaling.v2beta2.outputs.MetricTarget getTarget() {
        return this.target;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ResourceMetricSource defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private String name;
        private io.pulumi.kubernetes.autoscaling.v2beta2.outputs.MetricTarget target;

        public Builder() {
    	      // Empty
        }

        public Builder(ResourceMetricSource defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.name = defaults.name;
    	      this.target = defaults.target;
        }

        public Builder setName(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }

        public Builder setTarget(io.pulumi.kubernetes.autoscaling.v2beta2.outputs.MetricTarget target) {
            this.target = Objects.requireNonNull(target);
            return this;
        }

        public ResourceMetricSource build() {
            return new ResourceMetricSource(name, target);
        }
    }
}
