// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.apiextensions.v1.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class CustomResourceDefinitionSpec {
    private final @Nullable io.pulumi.kubernetes.apiextensions.v1.outputs.CustomResourceConversion conversion;
    private final String group;
    private final io.pulumi.kubernetes.apiextensions.v1.outputs.CustomResourceDefinitionNames names;
    private final @Nullable Boolean preserveUnknownFields;
    private final String scope;
    private final List<io.pulumi.kubernetes.apiextensions.v1.outputs.CustomResourceDefinitionVersion> versions;

    @OutputCustomType.Constructor({"conversion","group","names","preserveUnknownFields","scope","versions"})
    private CustomResourceDefinitionSpec(
        @Nullable io.pulumi.kubernetes.apiextensions.v1.outputs.CustomResourceConversion conversion,
        String group,
        io.pulumi.kubernetes.apiextensions.v1.outputs.CustomResourceDefinitionNames names,
        @Nullable Boolean preserveUnknownFields,
        String scope,
        List<io.pulumi.kubernetes.apiextensions.v1.outputs.CustomResourceDefinitionVersion> versions) {
        this.conversion = conversion;
        this.group = Objects.requireNonNull(group);
        this.names = Objects.requireNonNull(names);
        this.preserveUnknownFields = preserveUnknownFields;
        this.scope = Objects.requireNonNull(scope);
        this.versions = Objects.requireNonNull(versions);
    }

    public Optional<io.pulumi.kubernetes.apiextensions.v1.outputs.CustomResourceConversion> getConversion() {
        return Optional.ofNullable(this.conversion);
    }
    public String getGroup() {
        return this.group;
    }
    public io.pulumi.kubernetes.apiextensions.v1.outputs.CustomResourceDefinitionNames getNames() {
        return this.names;
    }
    public Optional<Boolean> getPreserveUnknownFields() {
        return Optional.ofNullable(this.preserveUnknownFields);
    }
    public String getScope() {
        return this.scope;
    }
    public List<io.pulumi.kubernetes.apiextensions.v1.outputs.CustomResourceDefinitionVersion> getVersions() {
        return this.versions;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(CustomResourceDefinitionSpec defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable io.pulumi.kubernetes.apiextensions.v1.outputs.CustomResourceConversion conversion;
        private String group;
        private io.pulumi.kubernetes.apiextensions.v1.outputs.CustomResourceDefinitionNames names;
        private @Nullable Boolean preserveUnknownFields;
        private String scope;
        private List<io.pulumi.kubernetes.apiextensions.v1.outputs.CustomResourceDefinitionVersion> versions;

        public Builder() {
    	      // Empty
        }

        public Builder(CustomResourceDefinitionSpec defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.conversion = defaults.conversion;
    	      this.group = defaults.group;
    	      this.names = defaults.names;
    	      this.preserveUnknownFields = defaults.preserveUnknownFields;
    	      this.scope = defaults.scope;
    	      this.versions = defaults.versions;
        }

        public Builder setConversion(@Nullable io.pulumi.kubernetes.apiextensions.v1.outputs.CustomResourceConversion conversion) {
            this.conversion = conversion;
            return this;
        }

        public Builder setGroup(String group) {
            this.group = Objects.requireNonNull(group);
            return this;
        }

        public Builder setNames(io.pulumi.kubernetes.apiextensions.v1.outputs.CustomResourceDefinitionNames names) {
            this.names = Objects.requireNonNull(names);
            return this;
        }

        public Builder setPreserveUnknownFields(@Nullable Boolean preserveUnknownFields) {
            this.preserveUnknownFields = preserveUnknownFields;
            return this;
        }

        public Builder setScope(String scope) {
            this.scope = Objects.requireNonNull(scope);
            return this;
        }

        public Builder setVersions(List<io.pulumi.kubernetes.apiextensions.v1.outputs.CustomResourceDefinitionVersion> versions) {
            this.versions = Objects.requireNonNull(versions);
            return this;
        }

        public CustomResourceDefinitionSpec build() {
            return new CustomResourceDefinitionSpec(conversion, group, names, preserveUnknownFields, scope, versions);
        }
    }
}
