// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.networking.v1.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class IngressSpec {
    private final @Nullable io.pulumi.kubernetes.networking.v1.outputs.IngressBackend defaultBackend;
    private final @Nullable String ingressClassName;
    private final @Nullable List<io.pulumi.kubernetes.networking.v1.outputs.IngressRule> rules;
    private final @Nullable List<io.pulumi.kubernetes.networking.v1.outputs.IngressTLS> tls;

    @OutputCustomType.Constructor({"defaultBackend","ingressClassName","rules","tls"})
    private IngressSpec(
        @Nullable io.pulumi.kubernetes.networking.v1.outputs.IngressBackend defaultBackend,
        @Nullable String ingressClassName,
        @Nullable List<io.pulumi.kubernetes.networking.v1.outputs.IngressRule> rules,
        @Nullable List<io.pulumi.kubernetes.networking.v1.outputs.IngressTLS> tls) {
        this.defaultBackend = defaultBackend;
        this.ingressClassName = ingressClassName;
        this.rules = rules;
        this.tls = tls;
    }

    public Optional<io.pulumi.kubernetes.networking.v1.outputs.IngressBackend> getDefaultBackend() {
        return Optional.ofNullable(this.defaultBackend);
    }
    public Optional<String> getIngressClassName() {
        return Optional.ofNullable(this.ingressClassName);
    }
    public List<io.pulumi.kubernetes.networking.v1.outputs.IngressRule> getRules() {
        return this.rules == null ? List.of() : this.rules;
    }
    public List<io.pulumi.kubernetes.networking.v1.outputs.IngressTLS> getTls() {
        return this.tls == null ? List.of() : this.tls;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(IngressSpec defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable io.pulumi.kubernetes.networking.v1.outputs.IngressBackend defaultBackend;
        private @Nullable String ingressClassName;
        private @Nullable List<io.pulumi.kubernetes.networking.v1.outputs.IngressRule> rules;
        private @Nullable List<io.pulumi.kubernetes.networking.v1.outputs.IngressTLS> tls;

        public Builder() {
    	      // Empty
        }

        public Builder(IngressSpec defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.defaultBackend = defaults.defaultBackend;
    	      this.ingressClassName = defaults.ingressClassName;
    	      this.rules = defaults.rules;
    	      this.tls = defaults.tls;
        }

        public Builder setDefaultBackend(@Nullable io.pulumi.kubernetes.networking.v1.outputs.IngressBackend defaultBackend) {
            this.defaultBackend = defaultBackend;
            return this;
        }

        public Builder setIngressClassName(@Nullable String ingressClassName) {
            this.ingressClassName = ingressClassName;
            return this;
        }

        public Builder setRules(@Nullable List<io.pulumi.kubernetes.networking.v1.outputs.IngressRule> rules) {
            this.rules = rules;
            return this;
        }

        public Builder setTls(@Nullable List<io.pulumi.kubernetes.networking.v1.outputs.IngressTLS> tls) {
            this.tls = tls;
            return this;
        }

        public IngressSpec build() {
            return new IngressSpec(defaultBackend, ingressClassName, rules, tls);
        }
    }
}
