// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.core.v1.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class ClientIPConfig {
    private final @Nullable Integer timeoutSeconds;

    @OutputCustomType.Constructor({"timeoutSeconds"})
    private ClientIPConfig(@Nullable Integer timeoutSeconds) {
        this.timeoutSeconds = timeoutSeconds;
    }

    public Optional<Integer> getTimeoutSeconds() {
        return Optional.ofNullable(this.timeoutSeconds);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ClientIPConfig defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable Integer timeoutSeconds;

        public Builder() {
    	      // Empty
        }

        public Builder(ClientIPConfig defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.timeoutSeconds = defaults.timeoutSeconds;
        }

        public Builder setTimeoutSeconds(@Nullable Integer timeoutSeconds) {
            this.timeoutSeconds = timeoutSeconds;
            return this;
        }

        public ClientIPConfig build() {
            return new ClientIPConfig(timeoutSeconds);
        }
    }
}
