// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.core.v1.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class CSIPersistentVolumeSource {
    private final @Nullable io.pulumi.kubernetes.core.v1.outputs.SecretReference controllerExpandSecretRef;
    private final @Nullable io.pulumi.kubernetes.core.v1.outputs.SecretReference controllerPublishSecretRef;
    private final String driver;
    private final @Nullable String fsType;
    private final @Nullable io.pulumi.kubernetes.core.v1.outputs.SecretReference nodePublishSecretRef;
    private final @Nullable io.pulumi.kubernetes.core.v1.outputs.SecretReference nodeStageSecretRef;
    private final @Nullable Boolean readOnly;
    private final @Nullable Map<String,String> volumeAttributes;
    private final String volumeHandle;

    @OutputCustomType.Constructor({"controllerExpandSecretRef","controllerPublishSecretRef","driver","fsType","nodePublishSecretRef","nodeStageSecretRef","readOnly","volumeAttributes","volumeHandle"})
    private CSIPersistentVolumeSource(
        @Nullable io.pulumi.kubernetes.core.v1.outputs.SecretReference controllerExpandSecretRef,
        @Nullable io.pulumi.kubernetes.core.v1.outputs.SecretReference controllerPublishSecretRef,
        String driver,
        @Nullable String fsType,
        @Nullable io.pulumi.kubernetes.core.v1.outputs.SecretReference nodePublishSecretRef,
        @Nullable io.pulumi.kubernetes.core.v1.outputs.SecretReference nodeStageSecretRef,
        @Nullable Boolean readOnly,
        @Nullable Map<String,String> volumeAttributes,
        String volumeHandle) {
        this.controllerExpandSecretRef = controllerExpandSecretRef;
        this.controllerPublishSecretRef = controllerPublishSecretRef;
        this.driver = Objects.requireNonNull(driver);
        this.fsType = fsType;
        this.nodePublishSecretRef = nodePublishSecretRef;
        this.nodeStageSecretRef = nodeStageSecretRef;
        this.readOnly = readOnly;
        this.volumeAttributes = volumeAttributes;
        this.volumeHandle = Objects.requireNonNull(volumeHandle);
    }

    public Optional<io.pulumi.kubernetes.core.v1.outputs.SecretReference> getControllerExpandSecretRef() {
        return Optional.ofNullable(this.controllerExpandSecretRef);
    }
    public Optional<io.pulumi.kubernetes.core.v1.outputs.SecretReference> getControllerPublishSecretRef() {
        return Optional.ofNullable(this.controllerPublishSecretRef);
    }
    public String getDriver() {
        return this.driver;
    }
    public Optional<String> getFsType() {
        return Optional.ofNullable(this.fsType);
    }
    public Optional<io.pulumi.kubernetes.core.v1.outputs.SecretReference> getNodePublishSecretRef() {
        return Optional.ofNullable(this.nodePublishSecretRef);
    }
    public Optional<io.pulumi.kubernetes.core.v1.outputs.SecretReference> getNodeStageSecretRef() {
        return Optional.ofNullable(this.nodeStageSecretRef);
    }
    public Optional<Boolean> getReadOnly() {
        return Optional.ofNullable(this.readOnly);
    }
    public Map<String,String> getVolumeAttributes() {
        return this.volumeAttributes == null ? Map.of() : this.volumeAttributes;
    }
    public String getVolumeHandle() {
        return this.volumeHandle;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(CSIPersistentVolumeSource defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable io.pulumi.kubernetes.core.v1.outputs.SecretReference controllerExpandSecretRef;
        private @Nullable io.pulumi.kubernetes.core.v1.outputs.SecretReference controllerPublishSecretRef;
        private String driver;
        private @Nullable String fsType;
        private @Nullable io.pulumi.kubernetes.core.v1.outputs.SecretReference nodePublishSecretRef;
        private @Nullable io.pulumi.kubernetes.core.v1.outputs.SecretReference nodeStageSecretRef;
        private @Nullable Boolean readOnly;
        private @Nullable Map<String,String> volumeAttributes;
        private String volumeHandle;

        public Builder() {
    	      // Empty
        }

        public Builder(CSIPersistentVolumeSource defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.controllerExpandSecretRef = defaults.controllerExpandSecretRef;
    	      this.controllerPublishSecretRef = defaults.controllerPublishSecretRef;
    	      this.driver = defaults.driver;
    	      this.fsType = defaults.fsType;
    	      this.nodePublishSecretRef = defaults.nodePublishSecretRef;
    	      this.nodeStageSecretRef = defaults.nodeStageSecretRef;
    	      this.readOnly = defaults.readOnly;
    	      this.volumeAttributes = defaults.volumeAttributes;
    	      this.volumeHandle = defaults.volumeHandle;
        }

        public Builder setControllerExpandSecretRef(@Nullable io.pulumi.kubernetes.core.v1.outputs.SecretReference controllerExpandSecretRef) {
            this.controllerExpandSecretRef = controllerExpandSecretRef;
            return this;
        }

        public Builder setControllerPublishSecretRef(@Nullable io.pulumi.kubernetes.core.v1.outputs.SecretReference controllerPublishSecretRef) {
            this.controllerPublishSecretRef = controllerPublishSecretRef;
            return this;
        }

        public Builder setDriver(String driver) {
            this.driver = Objects.requireNonNull(driver);
            return this;
        }

        public Builder setFsType(@Nullable String fsType) {
            this.fsType = fsType;
            return this;
        }

        public Builder setNodePublishSecretRef(@Nullable io.pulumi.kubernetes.core.v1.outputs.SecretReference nodePublishSecretRef) {
            this.nodePublishSecretRef = nodePublishSecretRef;
            return this;
        }

        public Builder setNodeStageSecretRef(@Nullable io.pulumi.kubernetes.core.v1.outputs.SecretReference nodeStageSecretRef) {
            this.nodeStageSecretRef = nodeStageSecretRef;
            return this;
        }

        public Builder setReadOnly(@Nullable Boolean readOnly) {
            this.readOnly = readOnly;
            return this;
        }

        public Builder setVolumeAttributes(@Nullable Map<String,String> volumeAttributes) {
            this.volumeAttributes = volumeAttributes;
            return this;
        }

        public Builder setVolumeHandle(String volumeHandle) {
            this.volumeHandle = Objects.requireNonNull(volumeHandle);
            return this;
        }

        public CSIPersistentVolumeSource build() {
            return new CSIPersistentVolumeSource(controllerExpandSecretRef, controllerPublishSecretRef, driver, fsType, nodePublishSecretRef, nodeStageSecretRef, readOnly, volumeAttributes, volumeHandle);
        }
    }
}
