// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.core.v1.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class DownwardAPIVolumeFile {
    private final @Nullable io.pulumi.kubernetes.core.v1.outputs.ObjectFieldSelector fieldRef;
    private final @Nullable Integer mode;
    private final String path;
    private final @Nullable io.pulumi.kubernetes.core.v1.outputs.ResourceFieldSelector resourceFieldRef;

    @OutputCustomType.Constructor({"fieldRef","mode","path","resourceFieldRef"})
    private DownwardAPIVolumeFile(
        @Nullable io.pulumi.kubernetes.core.v1.outputs.ObjectFieldSelector fieldRef,
        @Nullable Integer mode,
        String path,
        @Nullable io.pulumi.kubernetes.core.v1.outputs.ResourceFieldSelector resourceFieldRef) {
        this.fieldRef = fieldRef;
        this.mode = mode;
        this.path = Objects.requireNonNull(path);
        this.resourceFieldRef = resourceFieldRef;
    }

    public Optional<io.pulumi.kubernetes.core.v1.outputs.ObjectFieldSelector> getFieldRef() {
        return Optional.ofNullable(this.fieldRef);
    }
    public Optional<Integer> getMode() {
        return Optional.ofNullable(this.mode);
    }
    public String getPath() {
        return this.path;
    }
    public Optional<io.pulumi.kubernetes.core.v1.outputs.ResourceFieldSelector> getResourceFieldRef() {
        return Optional.ofNullable(this.resourceFieldRef);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DownwardAPIVolumeFile defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable io.pulumi.kubernetes.core.v1.outputs.ObjectFieldSelector fieldRef;
        private @Nullable Integer mode;
        private String path;
        private @Nullable io.pulumi.kubernetes.core.v1.outputs.ResourceFieldSelector resourceFieldRef;

        public Builder() {
    	      // Empty
        }

        public Builder(DownwardAPIVolumeFile defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.fieldRef = defaults.fieldRef;
    	      this.mode = defaults.mode;
    	      this.path = defaults.path;
    	      this.resourceFieldRef = defaults.resourceFieldRef;
        }

        public Builder setFieldRef(@Nullable io.pulumi.kubernetes.core.v1.outputs.ObjectFieldSelector fieldRef) {
            this.fieldRef = fieldRef;
            return this;
        }

        public Builder setMode(@Nullable Integer mode) {
            this.mode = mode;
            return this;
        }

        public Builder setPath(String path) {
            this.path = Objects.requireNonNull(path);
            return this;
        }

        public Builder setResourceFieldRef(@Nullable io.pulumi.kubernetes.core.v1.outputs.ResourceFieldSelector resourceFieldRef) {
            this.resourceFieldRef = resourceFieldRef;
            return this;
        }

        public DownwardAPIVolumeFile build() {
            return new DownwardAPIVolumeFile(fieldRef, mode, path, resourceFieldRef);
        }
    }
}
