// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.core.v1.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class EndpointPort {
    private final @Nullable String appProtocol;
    private final @Nullable String name;
    private final Integer port;
    private final @Nullable String protocol;

    @OutputCustomType.Constructor({"appProtocol","name","port","protocol"})
    private EndpointPort(
        @Nullable String appProtocol,
        @Nullable String name,
        Integer port,
        @Nullable String protocol) {
        this.appProtocol = appProtocol;
        this.name = name;
        this.port = Objects.requireNonNull(port);
        this.protocol = protocol;
    }

    public Optional<String> getAppProtocol() {
        return Optional.ofNullable(this.appProtocol);
    }
    public Optional<String> getName() {
        return Optional.ofNullable(this.name);
    }
    public Integer getPort() {
        return this.port;
    }
    public Optional<String> getProtocol() {
        return Optional.ofNullable(this.protocol);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(EndpointPort defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable String appProtocol;
        private @Nullable String name;
        private Integer port;
        private @Nullable String protocol;

        public Builder() {
    	      // Empty
        }

        public Builder(EndpointPort defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.appProtocol = defaults.appProtocol;
    	      this.name = defaults.name;
    	      this.port = defaults.port;
    	      this.protocol = defaults.protocol;
        }

        public Builder setAppProtocol(@Nullable String appProtocol) {
            this.appProtocol = appProtocol;
            return this;
        }

        public Builder setName(@Nullable String name) {
            this.name = name;
            return this;
        }

        public Builder setPort(Integer port) {
            this.port = Objects.requireNonNull(port);
            return this;
        }

        public Builder setProtocol(@Nullable String protocol) {
            this.protocol = protocol;
            return this;
        }

        public EndpointPort build() {
            return new EndpointPort(appProtocol, name, port, protocol);
        }
    }
}
