// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.core.v1.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class EnvFromSource {
    private final @Nullable io.pulumi.kubernetes.core.v1.outputs.ConfigMapEnvSource configMapRef;
    private final @Nullable String prefix;
    private final @Nullable io.pulumi.kubernetes.core.v1.outputs.SecretEnvSource secretRef;

    @OutputCustomType.Constructor({"configMapRef","prefix","secretRef"})
    private EnvFromSource(
        @Nullable io.pulumi.kubernetes.core.v1.outputs.ConfigMapEnvSource configMapRef,
        @Nullable String prefix,
        @Nullable io.pulumi.kubernetes.core.v1.outputs.SecretEnvSource secretRef) {
        this.configMapRef = configMapRef;
        this.prefix = prefix;
        this.secretRef = secretRef;
    }

    public Optional<io.pulumi.kubernetes.core.v1.outputs.ConfigMapEnvSource> getConfigMapRef() {
        return Optional.ofNullable(this.configMapRef);
    }
    public Optional<String> getPrefix() {
        return Optional.ofNullable(this.prefix);
    }
    public Optional<io.pulumi.kubernetes.core.v1.outputs.SecretEnvSource> getSecretRef() {
        return Optional.ofNullable(this.secretRef);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(EnvFromSource defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable io.pulumi.kubernetes.core.v1.outputs.ConfigMapEnvSource configMapRef;
        private @Nullable String prefix;
        private @Nullable io.pulumi.kubernetes.core.v1.outputs.SecretEnvSource secretRef;

        public Builder() {
    	      // Empty
        }

        public Builder(EnvFromSource defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.configMapRef = defaults.configMapRef;
    	      this.prefix = defaults.prefix;
    	      this.secretRef = defaults.secretRef;
        }

        public Builder setConfigMapRef(@Nullable io.pulumi.kubernetes.core.v1.outputs.ConfigMapEnvSource configMapRef) {
            this.configMapRef = configMapRef;
            return this;
        }

        public Builder setPrefix(@Nullable String prefix) {
            this.prefix = prefix;
            return this;
        }

        public Builder setSecretRef(@Nullable io.pulumi.kubernetes.core.v1.outputs.SecretEnvSource secretRef) {
            this.secretRef = secretRef;
            return this;
        }

        public EnvFromSource build() {
            return new EnvFromSource(configMapRef, prefix, secretRef);
        }
    }
}
