// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.core.v1.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class EnvVarSource {
    private final @Nullable io.pulumi.kubernetes.core.v1.outputs.ConfigMapKeySelector configMapKeyRef;
    private final @Nullable io.pulumi.kubernetes.core.v1.outputs.ObjectFieldSelector fieldRef;
    private final @Nullable io.pulumi.kubernetes.core.v1.outputs.ResourceFieldSelector resourceFieldRef;
    private final @Nullable io.pulumi.kubernetes.core.v1.outputs.SecretKeySelector secretKeyRef;

    @OutputCustomType.Constructor({"configMapKeyRef","fieldRef","resourceFieldRef","secretKeyRef"})
    private EnvVarSource(
        @Nullable io.pulumi.kubernetes.core.v1.outputs.ConfigMapKeySelector configMapKeyRef,
        @Nullable io.pulumi.kubernetes.core.v1.outputs.ObjectFieldSelector fieldRef,
        @Nullable io.pulumi.kubernetes.core.v1.outputs.ResourceFieldSelector resourceFieldRef,
        @Nullable io.pulumi.kubernetes.core.v1.outputs.SecretKeySelector secretKeyRef) {
        this.configMapKeyRef = configMapKeyRef;
        this.fieldRef = fieldRef;
        this.resourceFieldRef = resourceFieldRef;
        this.secretKeyRef = secretKeyRef;
    }

    public Optional<io.pulumi.kubernetes.core.v1.outputs.ConfigMapKeySelector> getConfigMapKeyRef() {
        return Optional.ofNullable(this.configMapKeyRef);
    }
    public Optional<io.pulumi.kubernetes.core.v1.outputs.ObjectFieldSelector> getFieldRef() {
        return Optional.ofNullable(this.fieldRef);
    }
    public Optional<io.pulumi.kubernetes.core.v1.outputs.ResourceFieldSelector> getResourceFieldRef() {
        return Optional.ofNullable(this.resourceFieldRef);
    }
    public Optional<io.pulumi.kubernetes.core.v1.outputs.SecretKeySelector> getSecretKeyRef() {
        return Optional.ofNullable(this.secretKeyRef);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(EnvVarSource defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable io.pulumi.kubernetes.core.v1.outputs.ConfigMapKeySelector configMapKeyRef;
        private @Nullable io.pulumi.kubernetes.core.v1.outputs.ObjectFieldSelector fieldRef;
        private @Nullable io.pulumi.kubernetes.core.v1.outputs.ResourceFieldSelector resourceFieldRef;
        private @Nullable io.pulumi.kubernetes.core.v1.outputs.SecretKeySelector secretKeyRef;

        public Builder() {
    	      // Empty
        }

        public Builder(EnvVarSource defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.configMapKeyRef = defaults.configMapKeyRef;
    	      this.fieldRef = defaults.fieldRef;
    	      this.resourceFieldRef = defaults.resourceFieldRef;
    	      this.secretKeyRef = defaults.secretKeyRef;
        }

        public Builder setConfigMapKeyRef(@Nullable io.pulumi.kubernetes.core.v1.outputs.ConfigMapKeySelector configMapKeyRef) {
            this.configMapKeyRef = configMapKeyRef;
            return this;
        }

        public Builder setFieldRef(@Nullable io.pulumi.kubernetes.core.v1.outputs.ObjectFieldSelector fieldRef) {
            this.fieldRef = fieldRef;
            return this;
        }

        public Builder setResourceFieldRef(@Nullable io.pulumi.kubernetes.core.v1.outputs.ResourceFieldSelector resourceFieldRef) {
            this.resourceFieldRef = resourceFieldRef;
            return this;
        }

        public Builder setSecretKeyRef(@Nullable io.pulumi.kubernetes.core.v1.outputs.SecretKeySelector secretKeyRef) {
            this.secretKeyRef = secretKeyRef;
            return this;
        }

        public EnvVarSource build() {
            return new EnvVarSource(configMapKeyRef, fieldRef, resourceFieldRef, secretKeyRef);
        }
    }
}
