// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.core.v1.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class ExecAction {
    private final @Nullable List<String> command;

    @OutputCustomType.Constructor({"command"})
    private ExecAction(@Nullable List<String> command) {
        this.command = command;
    }

    public List<String> getCommand() {
        return this.command == null ? List.of() : this.command;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ExecAction defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable List<String> command;

        public Builder() {
    	      // Empty
        }

        public Builder(ExecAction defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.command = defaults.command;
        }

        public Builder setCommand(@Nullable List<String> command) {
            this.command = command;
            return this;
        }

        public ExecAction build() {
            return new ExecAction(command);
        }
    }
}
