// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.core.v1.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class Lifecycle {
    private final @Nullable io.pulumi.kubernetes.core.v1.outputs.Handler postStart;
    private final @Nullable io.pulumi.kubernetes.core.v1.outputs.Handler preStop;

    @OutputCustomType.Constructor({"postStart","preStop"})
    private Lifecycle(
        @Nullable io.pulumi.kubernetes.core.v1.outputs.Handler postStart,
        @Nullable io.pulumi.kubernetes.core.v1.outputs.Handler preStop) {
        this.postStart = postStart;
        this.preStop = preStop;
    }

    public Optional<io.pulumi.kubernetes.core.v1.outputs.Handler> getPostStart() {
        return Optional.ofNullable(this.postStart);
    }
    public Optional<io.pulumi.kubernetes.core.v1.outputs.Handler> getPreStop() {
        return Optional.ofNullable(this.preStop);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(Lifecycle defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable io.pulumi.kubernetes.core.v1.outputs.Handler postStart;
        private @Nullable io.pulumi.kubernetes.core.v1.outputs.Handler preStop;

        public Builder() {
    	      // Empty
        }

        public Builder(Lifecycle defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.postStart = defaults.postStart;
    	      this.preStop = defaults.preStop;
        }

        public Builder setPostStart(@Nullable io.pulumi.kubernetes.core.v1.outputs.Handler postStart) {
            this.postStart = postStart;
            return this;
        }

        public Builder setPreStop(@Nullable io.pulumi.kubernetes.core.v1.outputs.Handler preStop) {
            this.preStop = preStop;
            return this;
        }

        public Lifecycle build() {
            return new Lifecycle(postStart, preStop);
        }
    }
}
