// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.core.v1.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class LocalVolumeSource {
    private final @Nullable String fsType;
    private final String path;

    @OutputCustomType.Constructor({"fsType","path"})
    private LocalVolumeSource(
        @Nullable String fsType,
        String path) {
        this.fsType = fsType;
        this.path = Objects.requireNonNull(path);
    }

    public Optional<String> getFsType() {
        return Optional.ofNullable(this.fsType);
    }
    public String getPath() {
        return this.path;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(LocalVolumeSource defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable String fsType;
        private String path;

        public Builder() {
    	      // Empty
        }

        public Builder(LocalVolumeSource defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.fsType = defaults.fsType;
    	      this.path = defaults.path;
        }

        public Builder setFsType(@Nullable String fsType) {
            this.fsType = fsType;
            return this;
        }

        public Builder setPath(String path) {
            this.path = Objects.requireNonNull(path);
            return this;
        }

        public LocalVolumeSource build() {
            return new LocalVolumeSource(fsType, path);
        }
    }
}
