// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.core.v1.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class NamespaceStatus {
    private final @Nullable List<io.pulumi.kubernetes.core.v1.outputs.NamespaceCondition> conditions;
    private final @Nullable String phase;

    @OutputCustomType.Constructor({"conditions","phase"})
    private NamespaceStatus(
        @Nullable List<io.pulumi.kubernetes.core.v1.outputs.NamespaceCondition> conditions,
        @Nullable String phase) {
        this.conditions = conditions;
        this.phase = phase;
    }

    public List<io.pulumi.kubernetes.core.v1.outputs.NamespaceCondition> getConditions() {
        return this.conditions == null ? List.of() : this.conditions;
    }
    public Optional<String> getPhase() {
        return Optional.ofNullable(this.phase);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NamespaceStatus defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable List<io.pulumi.kubernetes.core.v1.outputs.NamespaceCondition> conditions;
        private @Nullable String phase;

        public Builder() {
    	      // Empty
        }

        public Builder(NamespaceStatus defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.conditions = defaults.conditions;
    	      this.phase = defaults.phase;
        }

        public Builder setConditions(@Nullable List<io.pulumi.kubernetes.core.v1.outputs.NamespaceCondition> conditions) {
            this.conditions = conditions;
            return this;
        }

        public Builder setPhase(@Nullable String phase) {
            this.phase = phase;
            return this;
        }

        public NamespaceStatus build() {
            return new NamespaceStatus(conditions, phase);
        }
    }
}
