// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.core.v1.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class NodeAffinity {
    private final @Nullable List<io.pulumi.kubernetes.core.v1.outputs.PreferredSchedulingTerm> preferredDuringSchedulingIgnoredDuringExecution;
    private final @Nullable io.pulumi.kubernetes.core.v1.outputs.NodeSelector requiredDuringSchedulingIgnoredDuringExecution;

    @OutputCustomType.Constructor({"preferredDuringSchedulingIgnoredDuringExecution","requiredDuringSchedulingIgnoredDuringExecution"})
    private NodeAffinity(
        @Nullable List<io.pulumi.kubernetes.core.v1.outputs.PreferredSchedulingTerm> preferredDuringSchedulingIgnoredDuringExecution,
        @Nullable io.pulumi.kubernetes.core.v1.outputs.NodeSelector requiredDuringSchedulingIgnoredDuringExecution) {
        this.preferredDuringSchedulingIgnoredDuringExecution = preferredDuringSchedulingIgnoredDuringExecution;
        this.requiredDuringSchedulingIgnoredDuringExecution = requiredDuringSchedulingIgnoredDuringExecution;
    }

    public List<io.pulumi.kubernetes.core.v1.outputs.PreferredSchedulingTerm> getPreferredDuringSchedulingIgnoredDuringExecution() {
        return this.preferredDuringSchedulingIgnoredDuringExecution == null ? List.of() : this.preferredDuringSchedulingIgnoredDuringExecution;
    }
    public Optional<io.pulumi.kubernetes.core.v1.outputs.NodeSelector> getRequiredDuringSchedulingIgnoredDuringExecution() {
        return Optional.ofNullable(this.requiredDuringSchedulingIgnoredDuringExecution);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NodeAffinity defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable List<io.pulumi.kubernetes.core.v1.outputs.PreferredSchedulingTerm> preferredDuringSchedulingIgnoredDuringExecution;
        private @Nullable io.pulumi.kubernetes.core.v1.outputs.NodeSelector requiredDuringSchedulingIgnoredDuringExecution;

        public Builder() {
    	      // Empty
        }

        public Builder(NodeAffinity defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.preferredDuringSchedulingIgnoredDuringExecution = defaults.preferredDuringSchedulingIgnoredDuringExecution;
    	      this.requiredDuringSchedulingIgnoredDuringExecution = defaults.requiredDuringSchedulingIgnoredDuringExecution;
        }

        public Builder setPreferredDuringSchedulingIgnoredDuringExecution(@Nullable List<io.pulumi.kubernetes.core.v1.outputs.PreferredSchedulingTerm> preferredDuringSchedulingIgnoredDuringExecution) {
            this.preferredDuringSchedulingIgnoredDuringExecution = preferredDuringSchedulingIgnoredDuringExecution;
            return this;
        }

        public Builder setRequiredDuringSchedulingIgnoredDuringExecution(@Nullable io.pulumi.kubernetes.core.v1.outputs.NodeSelector requiredDuringSchedulingIgnoredDuringExecution) {
            this.requiredDuringSchedulingIgnoredDuringExecution = requiredDuringSchedulingIgnoredDuringExecution;
            return this;
        }

        public NodeAffinity build() {
            return new NodeAffinity(preferredDuringSchedulingIgnoredDuringExecution, requiredDuringSchedulingIgnoredDuringExecution);
        }
    }
}
