// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.core.v1.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class PersistentVolumeClaimVolumeSource {
    private final String claimName;
    private final @Nullable Boolean readOnly;

    @OutputCustomType.Constructor({"claimName","readOnly"})
    private PersistentVolumeClaimVolumeSource(
        String claimName,
        @Nullable Boolean readOnly) {
        this.claimName = Objects.requireNonNull(claimName);
        this.readOnly = readOnly;
    }

    public String getClaimName() {
        return this.claimName;
    }
    public Optional<Boolean> getReadOnly() {
        return Optional.ofNullable(this.readOnly);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(PersistentVolumeClaimVolumeSource defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private String claimName;
        private @Nullable Boolean readOnly;

        public Builder() {
    	      // Empty
        }

        public Builder(PersistentVolumeClaimVolumeSource defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.claimName = defaults.claimName;
    	      this.readOnly = defaults.readOnly;
        }

        public Builder setClaimName(String claimName) {
            this.claimName = Objects.requireNonNull(claimName);
            return this;
        }

        public Builder setReadOnly(@Nullable Boolean readOnly) {
            this.readOnly = readOnly;
            return this;
        }

        public PersistentVolumeClaimVolumeSource build() {
            return new PersistentVolumeClaimVolumeSource(claimName, readOnly);
        }
    }
}
