// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.core.v1.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class PersistentVolumeClaimSpec {
    private final @Nullable List<String> accessModes;
    private final @Nullable io.pulumi.kubernetes.core.v1.outputs.TypedLocalObjectReference dataSource;
    private final @Nullable io.pulumi.kubernetes.core.v1.outputs.ResourceRequirements resources;
    private final @Nullable io.pulumi.kubernetes.meta.v1.outputs.LabelSelector selector;
    private final @Nullable String storageClassName;
    private final @Nullable String volumeMode;
    private final @Nullable String volumeName;

    @OutputCustomType.Constructor({"accessModes","dataSource","resources","selector","storageClassName","volumeMode","volumeName"})
    private PersistentVolumeClaimSpec(
        @Nullable List<String> accessModes,
        @Nullable io.pulumi.kubernetes.core.v1.outputs.TypedLocalObjectReference dataSource,
        @Nullable io.pulumi.kubernetes.core.v1.outputs.ResourceRequirements resources,
        @Nullable io.pulumi.kubernetes.meta.v1.outputs.LabelSelector selector,
        @Nullable String storageClassName,
        @Nullable String volumeMode,
        @Nullable String volumeName) {
        this.accessModes = accessModes;
        this.dataSource = dataSource;
        this.resources = resources;
        this.selector = selector;
        this.storageClassName = storageClassName;
        this.volumeMode = volumeMode;
        this.volumeName = volumeName;
    }

    public List<String> getAccessModes() {
        return this.accessModes == null ? List.of() : this.accessModes;
    }
    public Optional<io.pulumi.kubernetes.core.v1.outputs.TypedLocalObjectReference> getDataSource() {
        return Optional.ofNullable(this.dataSource);
    }
    public Optional<io.pulumi.kubernetes.core.v1.outputs.ResourceRequirements> getResources() {
        return Optional.ofNullable(this.resources);
    }
    public Optional<io.pulumi.kubernetes.meta.v1.outputs.LabelSelector> getSelector() {
        return Optional.ofNullable(this.selector);
    }
    public Optional<String> getStorageClassName() {
        return Optional.ofNullable(this.storageClassName);
    }
    public Optional<String> getVolumeMode() {
        return Optional.ofNullable(this.volumeMode);
    }
    public Optional<String> getVolumeName() {
        return Optional.ofNullable(this.volumeName);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(PersistentVolumeClaimSpec defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable List<String> accessModes;
        private @Nullable io.pulumi.kubernetes.core.v1.outputs.TypedLocalObjectReference dataSource;
        private @Nullable io.pulumi.kubernetes.core.v1.outputs.ResourceRequirements resources;
        private @Nullable io.pulumi.kubernetes.meta.v1.outputs.LabelSelector selector;
        private @Nullable String storageClassName;
        private @Nullable String volumeMode;
        private @Nullable String volumeName;

        public Builder() {
    	      // Empty
        }

        public Builder(PersistentVolumeClaimSpec defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accessModes = defaults.accessModes;
    	      this.dataSource = defaults.dataSource;
    	      this.resources = defaults.resources;
    	      this.selector = defaults.selector;
    	      this.storageClassName = defaults.storageClassName;
    	      this.volumeMode = defaults.volumeMode;
    	      this.volumeName = defaults.volumeName;
        }

        public Builder setAccessModes(@Nullable List<String> accessModes) {
            this.accessModes = accessModes;
            return this;
        }

        public Builder setDataSource(@Nullable io.pulumi.kubernetes.core.v1.outputs.TypedLocalObjectReference dataSource) {
            this.dataSource = dataSource;
            return this;
        }

        public Builder setResources(@Nullable io.pulumi.kubernetes.core.v1.outputs.ResourceRequirements resources) {
            this.resources = resources;
            return this;
        }

        public Builder setSelector(@Nullable io.pulumi.kubernetes.meta.v1.outputs.LabelSelector selector) {
            this.selector = selector;
            return this;
        }

        public Builder setStorageClassName(@Nullable String storageClassName) {
            this.storageClassName = storageClassName;
            return this;
        }

        public Builder setVolumeMode(@Nullable String volumeMode) {
            this.volumeMode = volumeMode;
            return this;
        }

        public Builder setVolumeName(@Nullable String volumeName) {
            this.volumeName = volumeName;
            return this;
        }

        public PersistentVolumeClaimSpec build() {
            return new PersistentVolumeClaimSpec(accessModes, dataSource, resources, selector, storageClassName, volumeMode, volumeName);
        }
    }
}
