// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.core.v1.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class PodAffinityTerm {
    private final @Nullable io.pulumi.kubernetes.meta.v1.outputs.LabelSelector labelSelector;
    private final @Nullable io.pulumi.kubernetes.meta.v1.outputs.LabelSelector namespaceSelector;
    private final @Nullable List<String> namespaces;
    private final String topologyKey;

    @OutputCustomType.Constructor({"labelSelector","namespaceSelector","namespaces","topologyKey"})
    private PodAffinityTerm(
        @Nullable io.pulumi.kubernetes.meta.v1.outputs.LabelSelector labelSelector,
        @Nullable io.pulumi.kubernetes.meta.v1.outputs.LabelSelector namespaceSelector,
        @Nullable List<String> namespaces,
        String topologyKey) {
        this.labelSelector = labelSelector;
        this.namespaceSelector = namespaceSelector;
        this.namespaces = namespaces;
        this.topologyKey = Objects.requireNonNull(topologyKey);
    }

    public Optional<io.pulumi.kubernetes.meta.v1.outputs.LabelSelector> getLabelSelector() {
        return Optional.ofNullable(this.labelSelector);
    }
    public Optional<io.pulumi.kubernetes.meta.v1.outputs.LabelSelector> getNamespaceSelector() {
        return Optional.ofNullable(this.namespaceSelector);
    }
    public List<String> getNamespaces() {
        return this.namespaces == null ? List.of() : this.namespaces;
    }
    public String getTopologyKey() {
        return this.topologyKey;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(PodAffinityTerm defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable io.pulumi.kubernetes.meta.v1.outputs.LabelSelector labelSelector;
        private @Nullable io.pulumi.kubernetes.meta.v1.outputs.LabelSelector namespaceSelector;
        private @Nullable List<String> namespaces;
        private String topologyKey;

        public Builder() {
    	      // Empty
        }

        public Builder(PodAffinityTerm defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.labelSelector = defaults.labelSelector;
    	      this.namespaceSelector = defaults.namespaceSelector;
    	      this.namespaces = defaults.namespaces;
    	      this.topologyKey = defaults.topologyKey;
        }

        public Builder setLabelSelector(@Nullable io.pulumi.kubernetes.meta.v1.outputs.LabelSelector labelSelector) {
            this.labelSelector = labelSelector;
            return this;
        }

        public Builder setNamespaceSelector(@Nullable io.pulumi.kubernetes.meta.v1.outputs.LabelSelector namespaceSelector) {
            this.namespaceSelector = namespaceSelector;
            return this;
        }

        public Builder setNamespaces(@Nullable List<String> namespaces) {
            this.namespaces = namespaces;
            return this;
        }

        public Builder setTopologyKey(String topologyKey) {
            this.topologyKey = Objects.requireNonNull(topologyKey);
            return this;
        }

        public PodAffinityTerm build() {
            return new PodAffinityTerm(labelSelector, namespaceSelector, namespaces, topologyKey);
        }
    }
}
