// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.core.v1.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class PortStatus {
    private final @Nullable String error;
    private final Integer port;
    private final String protocol;

    @OutputCustomType.Constructor({"error","port","protocol"})
    private PortStatus(
        @Nullable String error,
        Integer port,
        String protocol) {
        this.error = error;
        this.port = Objects.requireNonNull(port);
        this.protocol = Objects.requireNonNull(protocol);
    }

    public Optional<String> getError() {
        return Optional.ofNullable(this.error);
    }
    public Integer getPort() {
        return this.port;
    }
    public String getProtocol() {
        return this.protocol;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(PortStatus defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable String error;
        private Integer port;
        private String protocol;

        public Builder() {
    	      // Empty
        }

        public Builder(PortStatus defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.error = defaults.error;
    	      this.port = defaults.port;
    	      this.protocol = defaults.protocol;
        }

        public Builder setError(@Nullable String error) {
            this.error = error;
            return this;
        }

        public Builder setPort(Integer port) {
            this.port = Objects.requireNonNull(port);
            return this;
        }

        public Builder setProtocol(String protocol) {
            this.protocol = Objects.requireNonNull(protocol);
            return this;
        }

        public PortStatus build() {
            return new PortStatus(error, port, protocol);
        }
    }
}
