// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.core.v1.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class SecretVolumeSource {
    private final @Nullable Integer defaultMode;
    private final @Nullable List<io.pulumi.kubernetes.core.v1.outputs.KeyToPath> items;
    private final @Nullable Boolean optional;
    private final @Nullable String secretName;

    @OutputCustomType.Constructor({"defaultMode","items","optional","secretName"})
    private SecretVolumeSource(
        @Nullable Integer defaultMode,
        @Nullable List<io.pulumi.kubernetes.core.v1.outputs.KeyToPath> items,
        @Nullable Boolean optional,
        @Nullable String secretName) {
        this.defaultMode = defaultMode;
        this.items = items;
        this.optional = optional;
        this.secretName = secretName;
    }

    public Optional<Integer> getDefaultMode() {
        return Optional.ofNullable(this.defaultMode);
    }
    public List<io.pulumi.kubernetes.core.v1.outputs.KeyToPath> getItems() {
        return this.items == null ? List.of() : this.items;
    }
    public Optional<Boolean> getOptional() {
        return Optional.ofNullable(this.optional);
    }
    public Optional<String> getSecretName() {
        return Optional.ofNullable(this.secretName);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SecretVolumeSource defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable Integer defaultMode;
        private @Nullable List<io.pulumi.kubernetes.core.v1.outputs.KeyToPath> items;
        private @Nullable Boolean optional;
        private @Nullable String secretName;

        public Builder() {
    	      // Empty
        }

        public Builder(SecretVolumeSource defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.defaultMode = defaults.defaultMode;
    	      this.items = defaults.items;
    	      this.optional = defaults.optional;
    	      this.secretName = defaults.secretName;
        }

        public Builder setDefaultMode(@Nullable Integer defaultMode) {
            this.defaultMode = defaultMode;
            return this;
        }

        public Builder setItems(@Nullable List<io.pulumi.kubernetes.core.v1.outputs.KeyToPath> items) {
            this.items = items;
            return this;
        }

        public Builder setOptional(@Nullable Boolean optional) {
            this.optional = optional;
            return this;
        }

        public Builder setSecretName(@Nullable String secretName) {
            this.secretName = secretName;
            return this;
        }

        public SecretVolumeSource build() {
            return new SecretVolumeSource(defaultMode, items, optional, secretName);
        }
    }
}
