// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.core.v1.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class StorageOSPersistentVolumeSource {
    private final @Nullable String fsType;
    private final @Nullable Boolean readOnly;
    private final @Nullable io.pulumi.kubernetes.core.v1.outputs.ObjectReference secretRef;
    private final @Nullable String volumeName;
    private final @Nullable String volumeNamespace;

    @OutputCustomType.Constructor({"fsType","readOnly","secretRef","volumeName","volumeNamespace"})
    private StorageOSPersistentVolumeSource(
        @Nullable String fsType,
        @Nullable Boolean readOnly,
        @Nullable io.pulumi.kubernetes.core.v1.outputs.ObjectReference secretRef,
        @Nullable String volumeName,
        @Nullable String volumeNamespace) {
        this.fsType = fsType;
        this.readOnly = readOnly;
        this.secretRef = secretRef;
        this.volumeName = volumeName;
        this.volumeNamespace = volumeNamespace;
    }

    public Optional<String> getFsType() {
        return Optional.ofNullable(this.fsType);
    }
    public Optional<Boolean> getReadOnly() {
        return Optional.ofNullable(this.readOnly);
    }
    public Optional<io.pulumi.kubernetes.core.v1.outputs.ObjectReference> getSecretRef() {
        return Optional.ofNullable(this.secretRef);
    }
    public Optional<String> getVolumeName() {
        return Optional.ofNullable(this.volumeName);
    }
    public Optional<String> getVolumeNamespace() {
        return Optional.ofNullable(this.volumeNamespace);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(StorageOSPersistentVolumeSource defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable String fsType;
        private @Nullable Boolean readOnly;
        private @Nullable io.pulumi.kubernetes.core.v1.outputs.ObjectReference secretRef;
        private @Nullable String volumeName;
        private @Nullable String volumeNamespace;

        public Builder() {
    	      // Empty
        }

        public Builder(StorageOSPersistentVolumeSource defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.fsType = defaults.fsType;
    	      this.readOnly = defaults.readOnly;
    	      this.secretRef = defaults.secretRef;
    	      this.volumeName = defaults.volumeName;
    	      this.volumeNamespace = defaults.volumeNamespace;
        }

        public Builder setFsType(@Nullable String fsType) {
            this.fsType = fsType;
            return this;
        }

        public Builder setReadOnly(@Nullable Boolean readOnly) {
            this.readOnly = readOnly;
            return this;
        }

        public Builder setSecretRef(@Nullable io.pulumi.kubernetes.core.v1.outputs.ObjectReference secretRef) {
            this.secretRef = secretRef;
            return this;
        }

        public Builder setVolumeName(@Nullable String volumeName) {
            this.volumeName = volumeName;
            return this;
        }

        public Builder setVolumeNamespace(@Nullable String volumeNamespace) {
            this.volumeNamespace = volumeNamespace;
            return this;
        }

        public StorageOSPersistentVolumeSource build() {
            return new StorageOSPersistentVolumeSource(fsType, readOnly, secretRef, volumeName, volumeNamespace);
        }
    }
}
