// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.autoscaling.v2beta2.inputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;


public final class ExternalMetricStatusArgs extends io.pulumi.resources.ResourceArgs {

    public static final ExternalMetricStatusArgs Empty = new ExternalMetricStatusArgs();

    @InputImport(name="current", required=true)
    private final Input<io.pulumi.kubernetes.autoscaling.v2beta2.inputs.MetricValueStatusArgs> current;

    public Input<io.pulumi.kubernetes.autoscaling.v2beta2.inputs.MetricValueStatusArgs> getCurrent() {
        return this.current;
    }

    @InputImport(name="metric", required=true)
    private final Input<io.pulumi.kubernetes.autoscaling.v2beta2.inputs.MetricIdentifierArgs> metric;

    public Input<io.pulumi.kubernetes.autoscaling.v2beta2.inputs.MetricIdentifierArgs> getMetric() {
        return this.metric;
    }

    public ExternalMetricStatusArgs(
        Input<io.pulumi.kubernetes.autoscaling.v2beta2.inputs.MetricValueStatusArgs> current,
        Input<io.pulumi.kubernetes.autoscaling.v2beta2.inputs.MetricIdentifierArgs> metric) {
        this.current = Objects.requireNonNull(current, "expected parameter 'current' to be non-null");
        this.metric = Objects.requireNonNull(metric, "expected parameter 'metric' to be non-null");
    }

    private ExternalMetricStatusArgs() {
        this.current = Input.empty();
        this.metric = Input.empty();
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ExternalMetricStatusArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private Input<io.pulumi.kubernetes.autoscaling.v2beta2.inputs.MetricValueStatusArgs> current;
        private Input<io.pulumi.kubernetes.autoscaling.v2beta2.inputs.MetricIdentifierArgs> metric;

        public Builder() {
    	      // Empty
        }

        public Builder(ExternalMetricStatusArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.current = defaults.current;
    	      this.metric = defaults.metric;
        }

        public Builder setCurrent(Input<io.pulumi.kubernetes.autoscaling.v2beta2.inputs.MetricValueStatusArgs> current) {
            this.current = Objects.requireNonNull(current);
            return this;
        }

        public Builder setCurrent(io.pulumi.kubernetes.autoscaling.v2beta2.inputs.MetricValueStatusArgs current) {
            this.current = Input.of(Objects.requireNonNull(current));
            return this;
        }

        public Builder setMetric(Input<io.pulumi.kubernetes.autoscaling.v2beta2.inputs.MetricIdentifierArgs> metric) {
            this.metric = Objects.requireNonNull(metric);
            return this;
        }

        public Builder setMetric(io.pulumi.kubernetes.autoscaling.v2beta2.inputs.MetricIdentifierArgs metric) {
            this.metric = Input.of(Objects.requireNonNull(metric));
            return this;
        }

        public ExternalMetricStatusArgs build() {
            return new ExternalMetricStatusArgs(current, metric);
        }
    }
}
