// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.meta.v1.inputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;


public final class LabelSelectorArgs extends io.pulumi.resources.ResourceArgs {

    public static final LabelSelectorArgs Empty = new LabelSelectorArgs();

    @InputImport(name="matchExpressions")
    private final @Nullable Input<List<io.pulumi.kubernetes.meta.v1.inputs.LabelSelectorRequirementArgs>> matchExpressions;

    public Input<List<io.pulumi.kubernetes.meta.v1.inputs.LabelSelectorRequirementArgs>> getMatchExpressions() {
        return this.matchExpressions == null ? Input.empty() : this.matchExpressions;
    }

    @InputImport(name="matchLabels")
    private final @Nullable Input<Map<String,String>> matchLabels;

    public Input<Map<String,String>> getMatchLabels() {
        return this.matchLabels == null ? Input.empty() : this.matchLabels;
    }

    public LabelSelectorArgs(
        @Nullable Input<List<io.pulumi.kubernetes.meta.v1.inputs.LabelSelectorRequirementArgs>> matchExpressions,
        @Nullable Input<Map<String,String>> matchLabels) {
        this.matchExpressions = matchExpressions;
        this.matchLabels = matchLabels;
    }

    private LabelSelectorArgs() {
        this.matchExpressions = Input.empty();
        this.matchLabels = Input.empty();
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(LabelSelectorArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable Input<List<io.pulumi.kubernetes.meta.v1.inputs.LabelSelectorRequirementArgs>> matchExpressions;
        private @Nullable Input<Map<String,String>> matchLabels;

        public Builder() {
    	      // Empty
        }

        public Builder(LabelSelectorArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.matchExpressions = defaults.matchExpressions;
    	      this.matchLabels = defaults.matchLabels;
        }

        public Builder setMatchExpressions(@Nullable Input<List<io.pulumi.kubernetes.meta.v1.inputs.LabelSelectorRequirementArgs>> matchExpressions) {
            this.matchExpressions = matchExpressions;
            return this;
        }

        public Builder setMatchExpressions(@Nullable List<io.pulumi.kubernetes.meta.v1.inputs.LabelSelectorRequirementArgs> matchExpressions) {
            this.matchExpressions = Input.ofNullable(matchExpressions);
            return this;
        }

        public Builder setMatchLabels(@Nullable Input<Map<String,String>> matchLabels) {
            this.matchLabels = matchLabels;
            return this;
        }

        public Builder setMatchLabels(@Nullable Map<String,String> matchLabels) {
            this.matchLabels = Input.ofNullable(matchLabels);
            return this;
        }

        public LabelSelectorArgs build() {
            return new LabelSelectorArgs(matchExpressions, matchLabels);
        }
    }
}
