// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.node.v1alpha1.inputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;


public final class RuntimeClassSpecArgs extends io.pulumi.resources.ResourceArgs {

    public static final RuntimeClassSpecArgs Empty = new RuntimeClassSpecArgs();

    @InputImport(name="overhead")
    private final @Nullable Input<io.pulumi.kubernetes.node.v1alpha1.inputs.OverheadArgs> overhead;

    public Input<io.pulumi.kubernetes.node.v1alpha1.inputs.OverheadArgs> getOverhead() {
        return this.overhead == null ? Input.empty() : this.overhead;
    }

    @InputImport(name="runtimeHandler", required=true)
    private final Input<String> runtimeHandler;

    public Input<String> getRuntimeHandler() {
        return this.runtimeHandler;
    }

    @InputImport(name="scheduling")
    private final @Nullable Input<io.pulumi.kubernetes.node.v1alpha1.inputs.SchedulingArgs> scheduling;

    public Input<io.pulumi.kubernetes.node.v1alpha1.inputs.SchedulingArgs> getScheduling() {
        return this.scheduling == null ? Input.empty() : this.scheduling;
    }

    public RuntimeClassSpecArgs(
        @Nullable Input<io.pulumi.kubernetes.node.v1alpha1.inputs.OverheadArgs> overhead,
        Input<String> runtimeHandler,
        @Nullable Input<io.pulumi.kubernetes.node.v1alpha1.inputs.SchedulingArgs> scheduling) {
        this.overhead = overhead;
        this.runtimeHandler = Objects.requireNonNull(runtimeHandler, "expected parameter 'runtimeHandler' to be non-null");
        this.scheduling = scheduling;
    }

    private RuntimeClassSpecArgs() {
        this.overhead = Input.empty();
        this.runtimeHandler = Input.empty();
        this.scheduling = Input.empty();
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(RuntimeClassSpecArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable Input<io.pulumi.kubernetes.node.v1alpha1.inputs.OverheadArgs> overhead;
        private Input<String> runtimeHandler;
        private @Nullable Input<io.pulumi.kubernetes.node.v1alpha1.inputs.SchedulingArgs> scheduling;

        public Builder() {
    	      // Empty
        }

        public Builder(RuntimeClassSpecArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.overhead = defaults.overhead;
    	      this.runtimeHandler = defaults.runtimeHandler;
    	      this.scheduling = defaults.scheduling;
        }

        public Builder setOverhead(@Nullable Input<io.pulumi.kubernetes.node.v1alpha1.inputs.OverheadArgs> overhead) {
            this.overhead = overhead;
            return this;
        }

        public Builder setOverhead(@Nullable io.pulumi.kubernetes.node.v1alpha1.inputs.OverheadArgs overhead) {
            this.overhead = Input.ofNullable(overhead);
            return this;
        }

        public Builder setRuntimeHandler(Input<String> runtimeHandler) {
            this.runtimeHandler = Objects.requireNonNull(runtimeHandler);
            return this;
        }

        public Builder setRuntimeHandler(String runtimeHandler) {
            this.runtimeHandler = Input.of(Objects.requireNonNull(runtimeHandler));
            return this;
        }

        public Builder setScheduling(@Nullable Input<io.pulumi.kubernetes.node.v1alpha1.inputs.SchedulingArgs> scheduling) {
            this.scheduling = scheduling;
            return this;
        }

        public Builder setScheduling(@Nullable io.pulumi.kubernetes.node.v1alpha1.inputs.SchedulingArgs scheduling) {
            this.scheduling = Input.ofNullable(scheduling);
            return this;
        }

        public RuntimeClassSpecArgs build() {
            return new RuntimeClassSpecArgs(overhead, runtimeHandler, scheduling);
        }
    }
}
