// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.apiregistration.v1beta1;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;
import io.pulumi.kubernetes.apiregistration.v1beta1.inputs.*;

@ResourceType(type="kubernetes:apiregistration.k8s.io/v1beta1:APIServiceList")
public class APIServiceList extends io.pulumi.kubernetes.KubernetesResource {
    @OutputExport(name="apiVersion", type=String.class, parameters={})
    private Output</* @Nullable */ String> apiVersion;

    public Output</* @Nullable */ String> getApiVersion() {
        return this.apiVersion;
    }
    @OutputExport(name="items", type=List.class, parameters={io.pulumi.kubernetes.apiregistration.v1beta1.outputs.APIService.class})
    private Output<List<io.pulumi.kubernetes.apiregistration.v1beta1.outputs.APIService>> items;

    public Output<List<io.pulumi.kubernetes.apiregistration.v1beta1.outputs.APIService>> getItems() {
        return this.items;
    }
    @OutputExport(name="kind", type=String.class, parameters={})
    private Output</* @Nullable */ String> kind;

    public Output</* @Nullable */ String> getKind() {
        return this.kind;
    }
    @OutputExport(name="metadata", type=io.pulumi.kubernetes.meta.v1.outputs.ListMeta.class, parameters={})
    private Output</* @Nullable */ io.pulumi.kubernetes.meta.v1.outputs.ListMeta> metadata;

    public Output</* @Nullable */ io.pulumi.kubernetes.meta.v1.outputs.ListMeta> getMetadata() {
        return this.metadata;
    }

    public APIServiceList(String name, APIServiceListArgs args, @Nullable io.pulumi.resources.CustomResourceOptions options) {
        super("kubernetes:apiregistration.k8s.io/v1beta1:APIServiceList", name, makeArgs(args), makeResourceOptions(options, Input.empty()));
    }

    private APIServiceList(String name, Input<String> id, @Nullable io.pulumi.resources.CustomResourceOptions options) {
        super("kubernetes:apiregistration.k8s.io/v1beta1:APIServiceList", name, null, makeResourceOptions(options, id));
    }

    private static APIServiceListArgs makeArgs(APIServiceListArgs args) {
        var builder = args == null ? APIServiceListArgs.builder() : APIServiceListArgs.builder(args);
        return builder
            .setApiVersion("apiregistration.k8s.io/v1beta1")
            .setKind("APIServiceList")
            .build();
    }

    private static io.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable io.pulumi.resources.CustomResourceOptions options, @Nullable Input<String> id) {
        var defaultOptions = io.pulumi.resources.CustomResourceOptions.builder()
            .setVersion(Utilities.getVersion())
            .setAliases(List.of(
                Input.of(Alias.builder().setType("kubernetes:apiregistration/v1beta1:APIServiceList").build())
            ))
            .build();
        return io.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    public static APIServiceList get(String name, Input<String> id, @Nullable io.pulumi.resources.CustomResourceOptions options) {
        return new APIServiceList(name, id, options);
    }
}
