// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.policy.v1beta1;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;
import io.pulumi.kubernetes.policy.v1beta1.inputs.*;

@ResourceType(type="kubernetes:policy/v1beta1:PodSecurityPolicy")
public class PodSecurityPolicy extends io.pulumi.kubernetes.KubernetesResource {
    @OutputExport(name="apiVersion", type=String.class, parameters={})
    private Output</* @Nullable */ String> apiVersion;

    public Output</* @Nullable */ String> getApiVersion() {
        return this.apiVersion;
    }
    @OutputExport(name="kind", type=String.class, parameters={})
    private Output</* @Nullable */ String> kind;

    public Output</* @Nullable */ String> getKind() {
        return this.kind;
    }
    @OutputExport(name="metadata", type=io.pulumi.kubernetes.meta.v1.outputs.ObjectMeta.class, parameters={})
    private Output</* @Nullable */ io.pulumi.kubernetes.meta.v1.outputs.ObjectMeta> metadata;

    public Output</* @Nullable */ io.pulumi.kubernetes.meta.v1.outputs.ObjectMeta> getMetadata() {
        return this.metadata;
    }
    @OutputExport(name="spec", type=io.pulumi.kubernetes.policy.v1beta1.outputs.PodSecurityPolicySpec.class, parameters={})
    private Output</* @Nullable */ io.pulumi.kubernetes.policy.v1beta1.outputs.PodSecurityPolicySpec> spec;

    public Output</* @Nullable */ io.pulumi.kubernetes.policy.v1beta1.outputs.PodSecurityPolicySpec> getSpec() {
        return this.spec;
    }

    public PodSecurityPolicy(String name, @Nullable PodSecurityPolicyArgs args, @Nullable io.pulumi.resources.CustomResourceOptions options) {
        super("kubernetes:policy/v1beta1:PodSecurityPolicy", name, makeArgs(args), makeResourceOptions(options, Input.empty()));
    }

    private PodSecurityPolicy(String name, Input<String> id, @Nullable io.pulumi.resources.CustomResourceOptions options) {
        super("kubernetes:policy/v1beta1:PodSecurityPolicy", name, null, makeResourceOptions(options, id));
    }

    private static PodSecurityPolicyArgs makeArgs(@Nullable PodSecurityPolicyArgs args) {
        var builder = args == null ? PodSecurityPolicyArgs.builder() : PodSecurityPolicyArgs.builder(args);
        return builder
            .setApiVersion("policy/v1beta1")
            .setKind("PodSecurityPolicy")
            .build();
    }

    private static io.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable io.pulumi.resources.CustomResourceOptions options, @Nullable Input<String> id) {
        var defaultOptions = io.pulumi.resources.CustomResourceOptions.builder()
            .setVersion(Utilities.getVersion())
            .setAliases(List.of(
                Input.of(Alias.builder().setType("kubernetes:extensions/v1beta1:PodSecurityPolicy").build())
            ))
            .build();
        return io.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    public static PodSecurityPolicy get(String name, Input<String> id, @Nullable io.pulumi.resources.CustomResourceOptions options) {
        return new PodSecurityPolicy(name, id, options);
    }
}
