// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.storage.v1beta1.inputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;


public final class CSIDriverSpecArgs extends io.pulumi.resources.ResourceArgs {

    public static final CSIDriverSpecArgs Empty = new CSIDriverSpecArgs();

    @InputImport(name="attachRequired")
    private final @Nullable Input<Boolean> attachRequired;

    public Input<Boolean> getAttachRequired() {
        return this.attachRequired == null ? Input.empty() : this.attachRequired;
    }

    @InputImport(name="fsGroupPolicy")
    private final @Nullable Input<String> fsGroupPolicy;

    public Input<String> getFsGroupPolicy() {
        return this.fsGroupPolicy == null ? Input.empty() : this.fsGroupPolicy;
    }

    @InputImport(name="podInfoOnMount")
    private final @Nullable Input<Boolean> podInfoOnMount;

    public Input<Boolean> getPodInfoOnMount() {
        return this.podInfoOnMount == null ? Input.empty() : this.podInfoOnMount;
    }

    @InputImport(name="requiresRepublish")
    private final @Nullable Input<Boolean> requiresRepublish;

    public Input<Boolean> getRequiresRepublish() {
        return this.requiresRepublish == null ? Input.empty() : this.requiresRepublish;
    }

    @InputImport(name="storageCapacity")
    private final @Nullable Input<Boolean> storageCapacity;

    public Input<Boolean> getStorageCapacity() {
        return this.storageCapacity == null ? Input.empty() : this.storageCapacity;
    }

    @InputImport(name="tokenRequests")
    private final @Nullable Input<List<io.pulumi.kubernetes.storage.v1beta1.inputs.TokenRequestArgs>> tokenRequests;

    public Input<List<io.pulumi.kubernetes.storage.v1beta1.inputs.TokenRequestArgs>> getTokenRequests() {
        return this.tokenRequests == null ? Input.empty() : this.tokenRequests;
    }

    @InputImport(name="volumeLifecycleModes")
    private final @Nullable Input<List<String>> volumeLifecycleModes;

    public Input<List<String>> getVolumeLifecycleModes() {
        return this.volumeLifecycleModes == null ? Input.empty() : this.volumeLifecycleModes;
    }

    public CSIDriverSpecArgs(
        @Nullable Input<Boolean> attachRequired,
        @Nullable Input<String> fsGroupPolicy,
        @Nullable Input<Boolean> podInfoOnMount,
        @Nullable Input<Boolean> requiresRepublish,
        @Nullable Input<Boolean> storageCapacity,
        @Nullable Input<List<io.pulumi.kubernetes.storage.v1beta1.inputs.TokenRequestArgs>> tokenRequests,
        @Nullable Input<List<String>> volumeLifecycleModes) {
        this.attachRequired = attachRequired;
        this.fsGroupPolicy = fsGroupPolicy;
        this.podInfoOnMount = podInfoOnMount;
        this.requiresRepublish = requiresRepublish;
        this.storageCapacity = storageCapacity;
        this.tokenRequests = tokenRequests;
        this.volumeLifecycleModes = volumeLifecycleModes;
    }

    private CSIDriverSpecArgs() {
        this.attachRequired = Input.empty();
        this.fsGroupPolicy = Input.empty();
        this.podInfoOnMount = Input.empty();
        this.requiresRepublish = Input.empty();
        this.storageCapacity = Input.empty();
        this.tokenRequests = Input.empty();
        this.volumeLifecycleModes = Input.empty();
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(CSIDriverSpecArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable Input<Boolean> attachRequired;
        private @Nullable Input<String> fsGroupPolicy;
        private @Nullable Input<Boolean> podInfoOnMount;
        private @Nullable Input<Boolean> requiresRepublish;
        private @Nullable Input<Boolean> storageCapacity;
        private @Nullable Input<List<io.pulumi.kubernetes.storage.v1beta1.inputs.TokenRequestArgs>> tokenRequests;
        private @Nullable Input<List<String>> volumeLifecycleModes;

        public Builder() {
    	      // Empty
        }

        public Builder(CSIDriverSpecArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.attachRequired = defaults.attachRequired;
    	      this.fsGroupPolicy = defaults.fsGroupPolicy;
    	      this.podInfoOnMount = defaults.podInfoOnMount;
    	      this.requiresRepublish = defaults.requiresRepublish;
    	      this.storageCapacity = defaults.storageCapacity;
    	      this.tokenRequests = defaults.tokenRequests;
    	      this.volumeLifecycleModes = defaults.volumeLifecycleModes;
        }

        public Builder setAttachRequired(@Nullable Input<Boolean> attachRequired) {
            this.attachRequired = attachRequired;
            return this;
        }

        public Builder setAttachRequired(@Nullable Boolean attachRequired) {
            this.attachRequired = Input.ofNullable(attachRequired);
            return this;
        }

        public Builder setFsGroupPolicy(@Nullable Input<String> fsGroupPolicy) {
            this.fsGroupPolicy = fsGroupPolicy;
            return this;
        }

        public Builder setFsGroupPolicy(@Nullable String fsGroupPolicy) {
            this.fsGroupPolicy = Input.ofNullable(fsGroupPolicy);
            return this;
        }

        public Builder setPodInfoOnMount(@Nullable Input<Boolean> podInfoOnMount) {
            this.podInfoOnMount = podInfoOnMount;
            return this;
        }

        public Builder setPodInfoOnMount(@Nullable Boolean podInfoOnMount) {
            this.podInfoOnMount = Input.ofNullable(podInfoOnMount);
            return this;
        }

        public Builder setRequiresRepublish(@Nullable Input<Boolean> requiresRepublish) {
            this.requiresRepublish = requiresRepublish;
            return this;
        }

        public Builder setRequiresRepublish(@Nullable Boolean requiresRepublish) {
            this.requiresRepublish = Input.ofNullable(requiresRepublish);
            return this;
        }

        public Builder setStorageCapacity(@Nullable Input<Boolean> storageCapacity) {
            this.storageCapacity = storageCapacity;
            return this;
        }

        public Builder setStorageCapacity(@Nullable Boolean storageCapacity) {
            this.storageCapacity = Input.ofNullable(storageCapacity);
            return this;
        }

        public Builder setTokenRequests(@Nullable Input<List<io.pulumi.kubernetes.storage.v1beta1.inputs.TokenRequestArgs>> tokenRequests) {
            this.tokenRequests = tokenRequests;
            return this;
        }

        public Builder setTokenRequests(@Nullable List<io.pulumi.kubernetes.storage.v1beta1.inputs.TokenRequestArgs> tokenRequests) {
            this.tokenRequests = Input.ofNullable(tokenRequests);
            return this;
        }

        public Builder setVolumeLifecycleModes(@Nullable Input<List<String>> volumeLifecycleModes) {
            this.volumeLifecycleModes = volumeLifecycleModes;
            return this;
        }

        public Builder setVolumeLifecycleModes(@Nullable List<String> volumeLifecycleModes) {
            this.volumeLifecycleModes = Input.ofNullable(volumeLifecycleModes);
            return this;
        }

        public CSIDriverSpecArgs build() {
            return new CSIDriverSpecArgs(attachRequired, fsGroupPolicy, podInfoOnMount, requiresRepublish, storageCapacity, tokenRequests, volumeLifecycleModes);
        }
    }
}
