// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.storage.v1beta1.inputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;


public final class CSINodeDriverArgs extends io.pulumi.resources.ResourceArgs {

    public static final CSINodeDriverArgs Empty = new CSINodeDriverArgs();

    @InputImport(name="allocatable")
    private final @Nullable Input<io.pulumi.kubernetes.storage.v1beta1.inputs.VolumeNodeResourcesArgs> allocatable;

    public Input<io.pulumi.kubernetes.storage.v1beta1.inputs.VolumeNodeResourcesArgs> getAllocatable() {
        return this.allocatable == null ? Input.empty() : this.allocatable;
    }

    @InputImport(name="name", required=true)
    private final Input<String> name;

    public Input<String> getName() {
        return this.name;
    }

    @InputImport(name="nodeID", required=true)
    private final Input<String> nodeID;

    public Input<String> getNodeID() {
        return this.nodeID;
    }

    @InputImport(name="topologyKeys")
    private final @Nullable Input<List<String>> topologyKeys;

    public Input<List<String>> getTopologyKeys() {
        return this.topologyKeys == null ? Input.empty() : this.topologyKeys;
    }

    public CSINodeDriverArgs(
        @Nullable Input<io.pulumi.kubernetes.storage.v1beta1.inputs.VolumeNodeResourcesArgs> allocatable,
        Input<String> name,
        Input<String> nodeID,
        @Nullable Input<List<String>> topologyKeys) {
        this.allocatable = allocatable;
        this.name = Objects.requireNonNull(name, "expected parameter 'name' to be non-null");
        this.nodeID = Objects.requireNonNull(nodeID, "expected parameter 'nodeID' to be non-null");
        this.topologyKeys = topologyKeys;
    }

    private CSINodeDriverArgs() {
        this.allocatable = Input.empty();
        this.name = Input.empty();
        this.nodeID = Input.empty();
        this.topologyKeys = Input.empty();
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(CSINodeDriverArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable Input<io.pulumi.kubernetes.storage.v1beta1.inputs.VolumeNodeResourcesArgs> allocatable;
        private Input<String> name;
        private Input<String> nodeID;
        private @Nullable Input<List<String>> topologyKeys;

        public Builder() {
    	      // Empty
        }

        public Builder(CSINodeDriverArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.allocatable = defaults.allocatable;
    	      this.name = defaults.name;
    	      this.nodeID = defaults.nodeID;
    	      this.topologyKeys = defaults.topologyKeys;
        }

        public Builder setAllocatable(@Nullable Input<io.pulumi.kubernetes.storage.v1beta1.inputs.VolumeNodeResourcesArgs> allocatable) {
            this.allocatable = allocatable;
            return this;
        }

        public Builder setAllocatable(@Nullable io.pulumi.kubernetes.storage.v1beta1.inputs.VolumeNodeResourcesArgs allocatable) {
            this.allocatable = Input.ofNullable(allocatable);
            return this;
        }

        public Builder setName(Input<String> name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }

        public Builder setName(String name) {
            this.name = Input.of(Objects.requireNonNull(name));
            return this;
        }

        public Builder setNodeID(Input<String> nodeID) {
            this.nodeID = Objects.requireNonNull(nodeID);
            return this;
        }

        public Builder setNodeID(String nodeID) {
            this.nodeID = Input.of(Objects.requireNonNull(nodeID));
            return this;
        }

        public Builder setTopologyKeys(@Nullable Input<List<String>> topologyKeys) {
            this.topologyKeys = topologyKeys;
            return this;
        }

        public Builder setTopologyKeys(@Nullable List<String> topologyKeys) {
            this.topologyKeys = Input.ofNullable(topologyKeys);
            return this;
        }

        public CSINodeDriverArgs build() {
            return new CSINodeDriverArgs(allocatable, name, nodeID, topologyKeys);
        }
    }
}
