// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.kubernetes.auditregistration.v1alpha1.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import io.pulumi.kubernetes.Utilities;

@OutputCustomType
public final class WebhookThrottleConfig {
    private final @Nullable Integer burst;
    private final @Nullable Integer qps;

    @OutputCustomType.Constructor({"burst","qps"})
    private WebhookThrottleConfig(
        @Nullable Integer burst,
        @Nullable Integer qps) {
        this.burst = burst;
        this.qps = qps;
    }

    public Optional<Integer> getBurst() {
        return Optional.ofNullable(this.burst);
    }
    public Optional<Integer> getQps() {
        return Optional.ofNullable(this.qps);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(WebhookThrottleConfig defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable Integer burst;
        private @Nullable Integer qps;

        public Builder() {
    	      // Empty
        }

        public Builder(WebhookThrottleConfig defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.burst = defaults.burst;
    	      this.qps = defaults.qps;
        }

        public Builder setBurst(@Nullable Integer burst) {
            this.burst = burst;
            return this;
        }

        public Builder setQps(@Nullable Integer qps) {
            this.qps = qps;
            return this;
        }

        public WebhookThrottleConfig build() {
            return new WebhookThrottleConfig(burst, qps);
        }
    }
}
